Health-Education-England/tis-trainee-ui

.github/workflows/analyze-with-sonarqube.yml, sonar-project.properties
Create a basic workflow using the SonarCloud action.
TISNEW-3874
=> chore: Set up GitHub workflow to run SonarQube

.eslintrc, package.json, src/redux/store/store.ts
to get the trainee-ui frontend working in the pipeline
=> worked with Babul to apply these changes

src/services/FormRPartAService.ts, src/services/TraineeProfileService.ts, src/services/TraineeReferenceService.ts, src/services/apiService.ts
=> fix: Updated services to use context paths in url

src/components/forms/formr-part-a/ProfileToFormRPartAInitialValuesMapping.ts, src/models/ProgrammeMembership.ts
=> refactor: move programmeCompletionDate to programmeMembership level

src/components/forms/WarningMessage.tsx, src/components/forms/formr-part-b/Create.tsx, src/components/forms/formr-part-b/ValidationSchema.ts, src/components/forms/formr-part-b/View.tsx
* Updated warning message text
* Enforcing selection when program / local office is not found in reference data
=> Validation and label name fixes

src/components/forms/formr-part-a/ProfileToFormRPartAInitialValuesMapping.ts, src/components/forms/formr-part-a/__test__/ProfileToFormRPartAInitialValuesMapping.test.ts
Email should be left blank and not populated.
<no-ticket>
=> fix: leave email field blank

src/components/forms/formr-part-b/Create.tsx
* Added options check for prevRevalBody
=> Fixed local office name selection

src/components/forms/SelectInputField.tsx, src/components/forms/formr-part-b/Sections/Section2.tsx, src/components/forms/formr-part-b/Sections/WorkPanel.tsx, src/components/forms/formr-part-b/ValidationSchema.ts, src/models/FormRPartB.ts, src/models/Placement.ts, src/models/ProfileToFormRPartBInitialValues.ts, src/models/__test__/ProfileToFormRPartBInitialValues.test.ts
* Renamed placementType to typeOfWork
TISNEW-4445
=> feat: Mapped placements to work in form-r part-b Section2

.gitignore, README.md, cypress.json, cypress/integration/login/login.spec.ts, cypress/integration/profile/profile.spec.ts, src/components/profile/Profile.tsx
- Fix failing E2E tests following updates to Profile section
- Update README
=> fix: E2E tests

cypress.json, cypress/integration/formr-a/formr-a.spec.ts, cypress/integration/formr-b/formr-b.spec.ts, cypress/integration/login/login.spec.ts, cypress/integration/navbar/mobile-navbar.spec.ts, cypress/support/index.js, src/components/forms/CreateConfirm.tsx, src/components/forms/CreateList.tsx, src/components/forms/MultiChoiceInputField.tsx, src/components/forms/SelectInputField.tsx, src/components/forms/TextInputField.tsx, src/components/forms/formr-part-a/Create.tsx, src/components/forms/formr-part-a/View.tsx, src/components/forms/formr-part-b/Confirm.tsx, src/components/forms/formr-part-b/Sections/Section1.tsx, src/components/forms/formr-part-b/Sections/Section2.tsx, src/components/forms/formr-part-b/Sections/Section3.tsx, src/components/forms/formr-part-b/Sections/WorkPanel.tsx, src/components/forms/formr-part-b/View.tsx, src/components/navigation/Navbar.tsx
- Add e2e tests for form R section 3
- Add more tests to section 2
- Some refactoring of existing tests
- Fix some bugs with existing tests now failing intermittently. One issue was the view not defaulting to mobile view when required. This issue was fixed by removing this command from the the cypress index file and running it separately in each test file that required a mobile view.  
Ticket: TISNEW-4315
=> Add more e2e tests to Form R PartB

src/App.tsx, src/components/forms/MultiChoiceInputField.tsx, src/components/forms/formr-part-a/Create.tsx, src/components/forms/formr-part-a/ValidationSchema.ts, src/components/forms/formr-part-a/View.tsx, src/components/forms/formr-part-b/Confirm.tsx, src/components/forms/formr-part-b/Create.tsx, src/components/forms/formr-part-b/FormRPartB.module.scss, src/components/forms/formr-part-b/Sections/DeclarationPanel.tsx, src/components/forms/formr-part-b/Sections/Section3.tsx, src/components/forms/formr-part-b/Sections/Section4.tsx, src/components/forms/formr-part-b/Sections/Section5.tsx, src/components/forms/formr-part-b/ValidationSchema.ts, src/components/forms/formr-part-b/View.tsx, src/components/forms/formr-part-b/__test__/Confirm.test.tsx, src/components/forms/formr-part-b/__test__/Section4.test.tsx, src/components/forms/formr-part-b/__test__/Section5.test.tsx, src/components/forms/formr-part-b/__test__/View.test.tsx, src/index.scss, src/mock-data/submitted-formr-partb.ts, src/models/FormRPartB.ts, src/models/ProfileToFormRPartAInitialValues.ts, src/models/ProfileToFormRPartBInitialValues.ts, src/models/__test__/ProfileToFormRPartBInitialValues.test.ts, src/redux/reducers/formr-partb-reducer.ts, src/services/TraineeReferenceService.ts, src/utilities/Constants.ts, src/utilities/DeclarationPanelUtilities.ts, src/utilities/__test__/DeclarationPanelUtilities.test.ts
- Added forms for both sections 4 & 5 including a shared declaration panel component
- Added both sections to view and confirm pages
- Created unit tests
https://hee-tis.atlassian.net/browse/TISNEW-4317
https://hee-tis.atlassian.net/browse/TISNEW-4323
=> Feature/formr - Add sections 4 & 5 to FormR Part B

cypress/integration/formr-b/formr-b.spec.ts, cypress/support/commands.js, cypress/support/index.d.ts
* Added case for logout and login
=> test: Updated formr-b save functionality test

.github/workflows/analyze-with-sonarqube.yml, .github/workflows/deploy.yml
=> chore: Add manual triggers to GitHub workflows

.github/workflows/deploy.yml
Added  step to run e2e test against pre-prod env in the self-service pipeline
=> test: Added step in pipeline to run cypress E2E test TISNEW-5277

.github/workflows/deploy.yml
Added install command to generates node_modules
=> test: Added install command to generates node_modules  TISNEW-5277

.github/workflows/deploy.yml
=> test: added multiline command TISNEW-5277

.github/workflows/analyze-with-sonarqube.yml
Update Node to v14.15.0 (LTS) 
TISNEW-5709
=> Update node version used for sonarqube analysis

.github/workflows/analyze-with-sonarqube.yml
=> chore: Update sonarcloud-github-action version

src/components/forms/formr-part-b/FormRPartB.module.scss, src/index.scss
-  fix minor duplication in scss files
(Also marked some code smells as 'false positive')
NO TICKET
=> fix: sonarcloud code smells

package-lock.json, package.json, src/__snapshots__/App.snapshot.spec.tsx.snap
- Type definition for react-helmet moved from dev dependency to prod
- No ticket
=> fix:move type definition from dev to prod

.github/workflows/deploy.yml
=> fix: Workflow formatting

.aws/task-definition-pre-prod.json, .aws/task-definition-prod.json, .github/workflows/deploy.yml
https://hee-tis.atlassian.net/browse/TIS21-1025
=> fix:update references to old ecr repo

.aws/task-definition-pre-prod.json, .aws/task-definition-prod.json
https://hee-tis.atlassian.net/browse/TIS21-1025
=> fix:update ref to tis-trainee-ui

.aws/task-definition-prod.json
TIS21-1020: Create production pipelines
=> fix: use existing log group

src/index.tsx
WIP - Need to push to pre-prod to check the fetch response from lambda
TICKET: TIS21-1241
=> chore: Add dynamic env vars

package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/forms/formr-part-b/Sections/CovidDeclaration.tsx, src/index.tsx
- Add FE logic to enable AWS Amplify Cognito (was tempted to call it Congito) to be dynamically configured based on the environment ("development", "preprod", "production")
TICKET: TIS21-1241
=> Enable dynamic env (config) variables

package-lock.json, package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/profile/placements/PlacementPanel.tsx
=> Fix  grade and placement type displayed in profile

package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/profile/programmes/ProgrammePanel.tsx
Start, end, completion dates and curricula formatting.
TIS21-66
=> feat: add programme membership data.

package-lock.json, src/components/common/PrivacyPolicy.tsx
- Fixed link
- Did a fresh npm install following package tidy so have included an updated package-lock
=> fix:updated link to records management policy

package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/utilities/DateUtilities.ts
- Increase date range validation from 10yrs to 25yrs
TIS21-1455
=> Amend date range validation **Merge previous PR first**

package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/forms/formr-part-b/Sections/Section1.tsx, src/components/forms/formr-part-b/ValidationSchema.ts, src/components/support/Support.tsx, src/components/support/SupportList.tsx, src/components/support/__test__/SupportList.test.tsx, src/models/FormRPartB.ts
- Set field to nullable/ not required
- Refactor Support (typo and info layout) and SupportList (allow for null render when contact is blank)
TIS21-1488
=> Fix: previous revalidation date validation bug

package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/support/SupportList.tsx, src/models/LocalOfficeContacts.ts
- Make support contact drop-down names readable on mobile view.
TIS21-1494
=> fix: abbreviate contact names for mobile view

package-lock.json, package.json
Reverts Health-Education-England/tis-trainee-ui#390
=> Revert "chore(deps): bump yup from 0.29.3 to 0.32.9"

.gitignore, README.md, package-lock.json, package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/forms/formr-part-b/Create.tsx, src/components/forms/formr-part-b/ValidationSchema.ts
- Bump Yup library to latest version (dependabot yup update failed due to a compilation error that had to be fixed manually)
- Update README - in particular, improve the instructions for running Cypress tests
- Quick fix for a Form R Part B page refresh/ hang   
TODO 
This scope of this ticket was a bit too big for 'Bitty work' so have left some commits off this PR (more PR's to follow) - which will also make things easier to test / revert if necessary. These include:
- Fix bug in Covid Declaration section to hide 'Reason for self-rate' box on initial render
- Refractor Form R Part B Create/ SelectInputField comps (conditionals)
TIS21-1595
=> Bump Yup library to latest version

cypress/support/commands.js, package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/forms/formr-part-b/Sections/CovidDeclaration.tsx, src/components/forms/formr-part-b/ValidationSchema.ts
**Covid section bugs**
- fix bug in Covid Declaration: Hide reason for self-rate box when no options clicked.
- fix validation bug: Hide error box when no errors highlighted
TIS21-1600
=> Fix Covid section bugs

package-lock.json, package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/forms/CreateList.tsx, src/components/forms/MultiChoiceInputField.tsx, src/components/forms/formr-part-b/Create.tsx, src/components/support/Support.tsx, src/utilities/ReferenceDataUtilities.ts, src/utilities/__test__/ReferenceDataUtilities.test.ts
Refactored some files to make sonarcloud happier (and make our code a bit more readable/ maintainable).
TIS21-1773
=> Fix some sonarcloud code smells

cypress/integration/formr-a/formr-a.spec.ts, package-lock.json, package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/forms/formr-part-a/Create.tsx, src/components/forms/formr-part-a/__test__/Create.cy-test.tsx
TIS21-1890
TODO: refactor test code to make it a bit DRYer
=> feat: replace Prog Spec dropdown with autocomplete

.github/workflows/deploy.yml, package.json
=> chore: Update yml file for new Cypress config

.github/workflows/deploy.yml, package.json
=> chore: Add debug to Cypress GHA

cypress/support/commands.js, package.json
=> test: Remove redundant test logic

.github/workflows/deploy.yml, package.json
=> chore: Remove debug from Cypress test run

package-lock.json, package.json, src/components/authentication/LoginNew.tsx
=> feat: Update header text on TOTP setup page

package-lock.json, package.json, src/components/forms/formr-part-b/ValidationSchema.ts
Not sure we need the max validation so removed it. Can always think of a number later if needed.
NO TICKET
=> fix: remove max work validation

package.json, src/components/authentication/Login.module.scss, src/components/authentication/LoginNew.tsx
Quick fix to:
- Add conditional WarningCallout message for 3-minute QR code expiry.
- Redo additional support messaging.
NO TICKET
=> feat: Update support info and QR code reload logic

package-lock.json, package.json, src/components/forms/formr-part-b/ValidationSchema.ts
=> fix: Add nullable to prevRevalBodyOther

package.json, src/App.scss, src/App.tsx, src/components/authentication/signup/Auth.module.scss
- Modal config is preventing scrolling to footer on mobile so switch to default.
=> fix: mobile view

.github/workflows/deploy.yml, .github/workflows/pr-analysis.yml, README.md
=> chore: Rename master to main

cypress/support/commands.js, package.json, src/components/forms/formr-part-b/ValidationSchema.ts
fix: update ValidationSchema to use 'IsPastDate' validation for date boxes
=> TIS21-1214 - Form R (Part B) Date Validation sections 4 & 5

cypress/integration/formr-a/formr-a.spec.ts, package-lock.json, package.json
=> fix: broken formr-a test

cypress/integration/formr-b/formr-b.spec.ts, src/components/forms/FormsListBtn.tsx
- Reset Form B state if navigate away from Create page without saving
- Reset will be needed for both forms when more work done on error msgs etc. so created a resetForm method.
NO TICKET
=> feat: Reset Form B state if navigate away from Create

package.json, src/components/support/Support.cy-test.tsx, src/models/LocalOfficeContacts.ts
New contact emails: 
1. Thames Valley: [Formr.tv@hee.nhs.uk](mailto:Formr.tv@hee.nhs.uk)
2. Wessex: [Formr.wx@hee.nhs.uk](mailto:Formr.wx@hee.nhs.uk)
TIS21-2798
=> chore: update support contact emails

package.json, src/models/ProfileToFormRPartBInitialValues.ts, src/utilities/StringUtilities.ts, src/utilities/__test__/StringUtilities.test.ts
=> feat: Hide nulls from concatenated string (Type of Work header)

package-lock.json, package.json, src/components/authentication/mfa/SetupMFA.tsx, src/components/authentication/signup/constants/AuthConstants.ts, src/components/authentication/signup/formFields/AuthFormFields.tsx, src/components/authentication/signup/header/AuthHeader.tsx
Also Reword text after removing some of the references to Trainee (as agreed).
TICKET TIS21-2945
=> Update sign-up/sign in warning and agreement text

cypress/integration/formr-b/formr-b.spec.ts, cypress/support/commands.js, package.json, src/components/forms/formr-part-b/ValidationSchema.ts, src/components/forms/formr-part-b/View.tsx, src/components/forms/formr-part-b/sections/CovidDeclaration.cy-test.tsx, src/components/forms/formr-part-b/sections/CovidDeclaration.tsx
Remove validation from supervisor name and email address in Covid Declaration
TIS21-3067
=> Remove validation from supervisor name and email address in covid declaration

package.json
=> fix: bump app version to ensure cache-busting

package-lock.json, package.json, src/components/forms/FieldWarningMsg.scss, src/components/forms/FieldWarningMsg.tsx, src/components/forms/formr-part-a/Create.cy-test.tsx, src/components/forms/formr-part-a/Create.tsx, src/models/FormRPartA.ts, src/utilities/Constants.ts, src/utilities/FormRUtilities.tsx, src/utilities/__test__/FormRUtilities.test.tsx
Add soft validation (via warning message) to allow progress/saving Form R (A) with a non-UK postcode.
TICKET TIS21-2910
=> Feat/add warning msg for non-UK postcode

package.json, src/browser-update-config.json
Set the safari version to latest given that v15 appears to show date and time fields correctly.
NO TICKET
=> chore: Add safari to browser update config

package-lock.json, package.json, src/components/authentication/mfa/SetupMFA.tsx, src/components/forms/formr-part-b/ValidationSchema.ts, src/components/support/Support.tsx, src/services/__test__/TraineeProfileService.test.ts, src/utilities/__test__/BooleanUtilities.test.ts
=> fix: various typos

package.json, src/components/forms/SubmittedFormsList.cy-test.tsx, src/components/forms/SubmittedFormsList.tsx
More of a stop-gap for a single condition where e.g. error or omission spotted.
But should help divert support traffic to LO while we agree problem statement for handling
submitted forms.
NO TICKET
=> feat: Add support info to amend submitted Form R

package.json, src/components/authentication/signup/constants/AuthConstants.ts, src/components/support/Support.cy-test.tsx, src/components/support/Support.tsx, src/components/support/SupportList.tsx
- Add tech support panel to Support page 
- Improve wording on SMS and TOTP log in confirm comps
TICKET TIS21-3186
=> feat: Add tech support panel

package.json, src/App.tsx, src/components/authentication/signup/constants/AuthConstants.ts, src/components/profile/Profile.cy-test.tsx, src/components/profile/personal-details/PersonalDetailsComponent.tsx
- Remove cypress test attributes from Profile text
- Make some more Cognito comp field labels/ other text clearer
TICKET TIS21-3227
=> Fix: Remove cypress test attributes from Profile text

package.json, src/models/LocalOfficeContacts.ts
LO feedback - update NW Support email
NO TICKET
=> chore: update NW support email

package.json, src/components/forms/formr-part-b/sections/Section2.tsx, src/mock-data/draft-formr-partb.ts, src/mock-data/work-placements-list.ts, src/models/ProfileToFormRPartBInitialValues.ts, src/utilities/ProfileUtilities.ts, src/utilities/__test__/ProfileUtilities.test.ts
On FormR PartB. It is possible for there to be multiple placements on
the same day (though this is an edge case for bad data).
TIS21-3361: Restrict the placements pre-populated on Form R Part B
=> Feat: only include next future placement in form R part B TIS21-3361

package.json, src/components/forms/formr-part-b/sections/Section2.tsx
Just the usual FE madness.
NO TICKET
=> Fix prettier compile error

package-lock.json, package.json, src/components/forms/formr-part-a/View.cy-test.tsx, src/components/forms/formr-part-a/View.tsx, src/components/forms/formr-part-b/View.tsx
=> Add date submitted stamp to both forms to be reflected in the PDFs

src/components/forms/formr-part-a/View.cy-test.tsx, src/components/forms/formr-part-a/View.tsx, src/components/forms/formr-part-b/viewSections/View.cy-test.tsx, src/components/forms/formr-part-b/viewSections/View.tsx, src/utilities/FormRUtilities.tsx
refactor the submission date methods into a FormR Utility and update tests
No-Ticket
=> refactor: create submission date utility and update references

.github/workflows/deploy.yml, .github/workflows/pr-analysis.yml, package.json
=> fix: update node version in deployment pipeline

.github/workflows/deploy.yml
also added browser name to slack message and removed always statment to  the backup artifacts stage.
=> change primary test browser to chrome,

.github/workflows/deploy-s3.yml
=> chore: add setup node steps with cache to s3 deploy

.github/workflows/deploy.yml
=> chore: fix workflow step name

.github/workflows/deploy-dsp-alpha.yml, .github/workflows/deploy.yml, .github/workflows/pr-analysis.yml
DSP alpha will be deployed from the `dsp-alpha` branch to the appropriate S3 bucket.
TIS21-3686
=> chore: add workflow to DSP alpha deployment

package-lock.json, package.json, src/components/navigation/HEEHeader.module.scss, src/components/navigation/HEEHeader.tsx
TIS-LAPLAND
Let tisss snow if you want to.
=> feat: make Christmas snow again

package-lock.json, package.json, src/components/common/AutocompleteSelect.tsx, src/components/forms/formr-part-a/Create.tsx, src/mock-data/submitted-formr-parta.ts
Remove the programmeSpecialty conditional mistakenly added. 
Refactor AutocompleteSelect comp so it can handle undefined value (if needed).
NO TICKET
=> fix: formr part a comp

package-lock.json, package.json, src/components/navigation/HEEHeader.module.scss, src/components/navigation/HEEHeader.tsx
NO TICKET
(🤞the tests fail so it sticks around a bit longer.)
=> chore: remove snow 😥

.github/workflows/deploy.yml, package.json
Add 'next export' cmd to generate static HTML files for cloudwatch / s3.
NO-TICKET
=> fix: app deploy

.github/workflows/deploy.yml
Cloudwatch can't handle [[...app]].html format.
NO-TICKET
=> fix: rename static html file

.github/workflows/deploy.yml
Looks like a Cypress GHA update should fix things https://github.com/cypress-io/github-action/issues/568#issuecomment-1154799709 .
(last PR for today 😄)
NO TICKET
=> fix: Cypress pipeline test run fail

components/forms/formr-part-a/FormRPartA.tsx, components/forms/formr-part-b/FormRPartB.tsx, cypress/component/authentication/ChooseMfa.cy.tsx, cypress/component/authentication/CreateTotp.cy.tsx, cypress/component/authentication/MFA.cy.tsx, cypress/component/forms/formr-part-a/FormRPartA.cy.tsx, cypress/component/forms/formr-part-b/FormRPartB.cy.tsx, package.json
These are no longer needed now that redux manages the user state.
TIS21-3995
=> fix: remove unused props

package.json, styles/globals.scss
=> chore: set NHS font-family

components/home/HomeHeaderSection.tsx, package-lock.json, package.json
Update home header text from feedback.
Bump some packages.
NO TICKET
=> feat: update home header text

components/dsp/CredentialVerify.tsx, package-lock.json, package.json
=> fix: credentialVerify btn text

.github/workflows/deploy-alpha.yml, .github/workflows/deploy.yml, .github/workflows/e2e-test.yml
=> chore: update `aws-actions/configure-aws-credentials` version

.github/workflows/pr-analysis.yml, components/common/PanelsCreator.tsx, components/programmes/ConditionsOfJoining.tsx, models/ProgrammeMembership.ts, package-lock.json, package.json, utilities/CojUtilities.ts, utilities/Constants.ts, utilities/__test__/CojUtilities.test.ts
Add a Conditions of Joining status to Programme Membership panels, show the signed date and Gold Guide version when signed. Otherwise show a status message dependant on the start date of the programme.
TIS21-4372
=> feat: add Conditions of Joining status to PMs

mock-data/trainee-profile.ts
Add conditionsOfJoining to mock profile data.
TIS21-4372
=> test: fix mock data

components/main/GlobalAlert.tsx, components/programmes/ConditionsOfJoining.tsx, cypress/component/main/GlobalAlert.cy.tsx, cypress/component/programmes/ConditionsOfJoining.cy.tsx, cypress/component/programmes/Programmes.cy.tsx, mock-data/trainee-profile.ts, package-lock.json, package.json, redux/slices/traineeProfileSlice.ts, styles/globals.scss
Refactor the rendering condition of GlobalAlert so that it is not rendered as a zero height element if the CojAlert is not rendered. This makes it more extensible in the future, where multiple alert types may be available.
TIS21-4454
TIS21-4373
=> refactor: GlobalAlert rendering

components/programmes/ConditionsOfJoining.tsx, cypress/component/programmes/Programmes.cy.tsx
=> add text link for viewing ReadOnly form

components/forms/FormSavePDF.tsx, components/forms/conditionOfJoining/CojView.tsx, components/forms/formr-part-a/View.tsx, components/forms/formr-part-b/viewSections/View.tsx, cypress/component/forms/FormSavePDF.cy.tsx, cypress/component/forms/formr-part-a/View.cy.tsx, cypress/component/forms/formr-part-b/View.cy.tsx, cypress/component/programmes/CoJReadOnlyView.cy.tsx, cypress/component/programmes/CojView.cy.tsx, package-lock.json, package.json
test: update tests
chore: bump version
refactor: make FormSavePDF more generic
TIS21-4536
=> feat: add print pdf component to CoJ readOnly

cypress/e2e/authenticator/Authenticator.spec.ts, package.json
=> fix: broken auth test

components/authentication/signup/header/AuthHeader.tsx, package.json
=> fix: remove beta message on sign in /sign up page

components/support/LoSupport.tsx, mock-data/combinedReferenceData.ts, package.json
Filter Defence and London LETBs
NO TICKET
=> fix: LO support select options

README.md
=> doc: add BrowserStack testing information in Readme

components/forms/StringValidationSchema.ts, components/forms/formr-part-b/ValidationSchema.ts, components/forms/formr-part-b/sections/WorkPanel.tsx, components/forms/formr-part-b/viewSections/ViewSection2.tsx, cypress/support/commands.ts, mock-data/draft-formr-partb.ts, mock-data/submitted-formr-partb.ts, mock-data/work-placements-list.ts, models/FormRPartB.ts, models/ProfileToFormRPartBInitialValues.ts, utilities/Constants.ts
=> feat: add siteKnownAs in Form R Part B (Type of work)

components/breadcrumbs/Breadcrumbs.tsx, components/home/HomeHeaderSection.tsx, components/home/TssUpdates.tsx, cypress/component/home/Home.cy.tsx, cypress/component/home/HomeHeaderSection.cy.tsx, cypress/component/home/TssUpdates.cy.tsx, cypress/e2e/home/Home.spec.ts, mock-data/tss-updates-wp.ts, models/WPPost.ts, package-lock.json, package.json, redux/slices/index.ts, redux/slices/tssUpdatesSlice.ts, services/TssUpdatesService.ts, styles/globals.scss
- Add a 'What's New' section on Home next to Welcome
- Display summary of 1 most recent post in this section
- Show 'no posts' message and 'couldn't show any posts' messages in this section for empty and error states respectively.
TIS21-4528
=> Add 'What's New' to TSS Home Page

components/authentication/signup/sharedPrimitives/AuthBtnLink.tsx, package.json
=> feat: update Sign-up and Log-in FAQ link to split pages

.github/workflows/deploy.yml
=> build: fix substitution

components/authentication/signup/constants/AuthConstants.ts, components/authentication/signup/formFields/AuthFormFields.tsx, cypress/e2e/authenticator/Authenticator.spec.ts, package-lock.json, package.json
- Sign up to create an account
- Login in to Sign in (Amplify comp default to ensure consistent wording for all click events etc.)
TIS21-4836
=> feat: update signup wording

components/authentication/signup/constants/AuthConstants.ts, components/authentication/signup/formFields/AuthFormFields.tsx, cypress/e2e/authenticator/Authenticator.spec.ts, package-lock.json, package.json
Reverts Health-Education-England/tis-trainee-ui#912
Reverting as this broke the build and another change to the workflow needs to be deployed to fix a prod issue.
=> Revert "feat: update signup wording"

.github/workflows/deploy-alpha.yml
=> build: deploy versioned app to alpha

.github/workflows/deploy-alpha.yml
=> build: use correct alpha origin id

components/app/CRAEntryPoint.tsx, components/authentication/signup/sharedPrimitives/AuthBtnLink.tsx, package.json
`Log in` to `Sign in`
`Sign up` to `Create an account`
TIS21-4832
TIS21-4867
=> fix: update email template wording

components/app/CRAEntryPoint.tsx, components/common/PanelsCreator.tsx, components/dsp/CredentialIssue.tsx, components/dsp/DspIssueBtn.tsx, components/forms/SelectInputField.tsx, components/forms/form-builder/form-fields/Selector.tsx, components/forms/formr-part-b/viewSections/ViewSection6.tsx, package-lock.json, package.json, utilities/FormRUtilities.tsx
Tech improvement (code smells)
- Fix most code smells
- Simplify displayListVal func by removing switch and make it type safe.
NO TICKET
=> chore: make sonarcloud happier - pt1

components/support/Support.tsx, cypress/component/support/Support.cy.tsx, package.json
=> fix: update FAQ link on support page

.github/workflows/deploy.yml, .github/workflows/e2e-test.yml, cypress.config.ts, package-lock.json, package.json
update references to trainee.tis.nhs.uk to the new URL of stage.trainee.tis.nhs.uk
ticket TIS21-4900
=> refactore: update references to baseUrl for preProd

.github/workflows/deploy-alpha.yml, .github/workflows/deploy.yml, .github/workflows/e2e-test.yml
=> build: use OIDC for AWS credentials

components/forms/StartOverButton.tsx, components/forms/form-builder/FormViewBuilder.tsx, package-lock.json, package.json
... on Form R A Confirm page (/confirm)
TIS21-4877
=> fix: 'Start over' button redirect

README.md, cypress/component/forms/formr-part-a/FormA.cy.tsx, cypress/e2e/authenticator/Authenticator.spec.ts, cypress/e2e/footer/Footer.spec.ts, cypress/e2e/formr-a/FormRA.spec.ts, cypress/e2e/formr-b/FormRB.spec.ts, cypress/e2e/home/Home.spec.ts, cypress/e2e/mfa/MFA.spec.ts, cypress/e2e/navbar/Navbar.spec.ts, cypress/e2e/placements/Placements.spec.ts, cypress/e2e/profile/Profile.spec.ts, cypress/e2e/programmes/Programmes.spec.ts, cypress/e2e/support/Chatbot.spec.ts, cypress/e2e/support/Support.spec.ts, cypress/support/commands.ts, cypress/support/index.d.ts, models/ProfileToFormRPartAInitialValues.ts, package.json
=> chore: deployment pipeline details

cypress/e2e/authenticator/Authenticator.spec.ts, cypress/e2e/formr-b/FormRB.spec.ts, package.json
=> fix: broken e2e tests

cypress/e2e/placements/Placements.spec.ts, package-lock.json
Subspecialty field not included if no specialty.
TIS21-4983
=> fix: postAllowsSubspecialty logic

package.json, utilities/Constants.ts
=> fix: update Yorkshire and the Humber support email address

components/placements/Specialty.tsx, cypress/component/placements/Placements.cy.tsx, mock-data/trainee-profile.ts, package-lock.json
Allow subspecialties to be shown if they exist, regardless of postAllowsSubspecialty.
TIS21-4983
=> fix: placement subspecialty display logic

cypress/component/placements/Placements.cy.tsx, package-lock.json
=> fix: test description

components/forms/form-builder/FormBuilder.tsx, components/main/Main.tsx, components/placements/OtherSites.tsx, cypress/support/commands.ts, package-lock.json, package.json
Separate comp logic into several functions to make it more readable/maintainable. 
Fix lint warning in Main comp and some code smells.
TIS21-5062
=> refactor: FormBuilder

components/support/__test__/LoSupport.test.tsx, package.json, utilities/Constants.ts
=> fix: update local office support email to nhs.net

.github/workflows/deploy-alpha.yml, .github/workflows/deploy.yml, .github/workflows/pr-analysis.yml, Dockerfile, package-lock.json, package.json
=> chore: update Node to LTS(18) and see what breaks

components/programmes/Programmes.tsx, models/Dsp.ts, package-lock.json, package.json
...to match Programme Membership API Gateway changes.
=> chore: update CredentialDspType

components/forms/formr-part-b/viewSections/ViewSection7.tsx, package.json
=> refactor: reword covid question in section 7 of formR partB

components/programmes/ConditionsOfJoining.tsx, package-lock.json, package.json, styles/globals.scss
=> feat: Replace the CoJ sign link with big green button

cypress/e2e/formr-b/FormRB.spec.ts
=> fix: fix failing e2e tests

components/forms/formr-part-b/Create.tsx, components/forms/formr-part-b/viewSections/View.tsx, cypress/component/forms/ProgressBar.cy.tsx, cypress/component/forms/formr-part-b/Create.cy.tsx, cypress/component/forms/formr-part-b/View.cy.tsx, mock-data/trainee-profile.ts, models/FormRPartB.ts, models/ProfileToFormRPartBInitialValues.ts, package-lock.json, package.json, utilities/FormRUtilities.tsx
this will need to be merged at the same time as the forms branch in order to test properly on stage (https://github.com/Health-Education-England/tis-trainee-forms/pull/590)
TIS21-5402
=> Feat  set covid flag to false

components/forms/form-builder/form-fields/Dates.tsx, components/forms/form-builder/form-r/part-a/formAValidationSchema.ts, components/forms/formr-part-b/ValidationSchema.ts, cypress/component/forms/formr-part-a/FormA.cy.tsx, cypress/e2e/formr-a/FormRA.spec.ts, package-lock.json, package.json, utilities/FormBuilderUtilities.ts
Replace react-datepicker with native date input/picker (used in form b).
Also add the date .typeError validation to form a and b schemas to improve error msg UX.
TIS21-5644
=> chore: replace react-datepicker

package-lock.json, package.json, utilities/FormBuilderUtilities.ts
hotfix for a type error introduced in the most recent PR
NO-TICKET
=> fix: type error for onKey handleKeyDown

components/forms/form-builder/FormBuilder.tsx, components/forms/form-builder/form-array/PanelBuilder.tsx, components/forms/form-builder/form-fields/Dates.tsx, components/forms/form-builder/form-fields/Text.tsx, components/forms/form-builder/form-fields/TextArea.tsx, package-lock.json, package.json, utilities/FormBuilderUtilities.ts
Another WIP commit, the main objective:
Similar to #1009,  make sure Form R A still works while adding the FormBuilder logic to allow for number, total and textarea fields which are needed to build Form B.
Tests to follow when we build Form B using FormBuilder - which is probably the next step.
Note: Built separate Text and TextArea comps for now but can merge them into one Text component if it makes more sense.
TIS21-4591
TIS21-5718
=> Refactor FormBuilder - part 2

components/common/ScrollToTop.tsx, components/common/__test__/ScrollToTop.test.tsx, components/forms/form-builder/FormBuilder.tsx, package-lock.json, package.json
The purpose of this commit is to provide consistent behaviour for all forms by adding the ScrollToTop to the FormBuilder. 
(The scrollToTop used to be on the old Form A and there is one on Form B.)
TIS21-5729
=> feat: Add ScrollToTop to FormBuilder

components/home/actionSummary/ActionSummary.tsx, components/main/GlobalAlert.tsx, cypress/component/home/action-summary/ActionSummary.cy.tsx, cypress/component/main/GlobalAlert.cy.tsx, cypress/component/placements/Placements.cy.tsx, mock-data/trainee-profile.ts, package.json, utilities/ActionSummaryUtilities.ts, utilities/hooks/action-summary/useOutstandingActions.ts
Just slip-streaming on from Doris's work 🌮  😅 
TIS21-5621
TIS21-5622
=> feat: placement action notifications

components/forms/form-builder/FormBuilder.tsx, components/forms/form-builder/form-fields/Checkboxes.tsx, components/forms/form-builder/form-fields/Dates.tsx, components/forms/form-builder/form-fields/Phone.tsx, components/forms/form-builder/form-fields/Radios.tsx, components/forms/form-builder/form-fields/Selector.tsx, components/forms/form-builder/form-fields/Text.tsx, components/forms/form-builder/form-fields/TextArea.tsx, package.json
Another wafer-thin slice to add a checkbox field option to the FormBuilder in preparation for building Form R Part B (so no implementation/ tests yet 😀).
TIS21-5755
=> chore: add checkbox field to form builder

cypress/e2e/formr-a/FormRA.spec.ts, package-lock.json, package.json
=> fix: form A test (form submission)

cypress/e2e/navbar/Navbar.spec.ts, package.json
The current styling markup is a little clumsy, but it is scheduled for revision, so I haven't done more than patch the e2e test error.
TIS21-5684
=> fix: navbar e2e test

cypress/e2e/notifications/Notifications.spec.ts, mock-data/notifications.ts, package-lock.json, package.json, redux/slices/notificationsSlice.ts
fix to filter the received notifications so that only those marked type "IN_APP" are displayed to the user to avoid being spammed by email notifications
TIS21-5685
=> Filter by notification type

cypress/e2e/notifications/Notifications.spec.ts, package-lock.json, package.json
…pire and endpoint wait into each test
NO_TICKET
=> Fix broken notification e2e test

cypress/component/programmes/ConditionsOfJoining.cy.tsx, package.json, utilities/CojUtilities.ts, utilities/__test__/CojUtilities.test.ts
Note, as discussed, the new-starter logic will be implemented separately as TIS21-5914
TIS21-5890
TIS21-5739
=> fix: remove 13-week CoJ signing horizon

components/notifications/NotificationMessageText.tsx, package.json
=> fix: link target to new tab for notifications

components/notifications/DebouncedInput.tsx, components/notifications/TablePagination.tsx, cypress.config.ts, package-lock.json, package.json, styles/globals.scss, utilities/ProfileUtilities.ts
fix: Align table pagination with the rest of the page (left margin); ditch the NHS grid stuff which is producing some clashes/weirdness and just use CSS flex on span to make it responsive.
fix: getRecentProgramme sonarcloud issue.
chore: increase defaultCommandTimeout to 30s to lessen e2e timeout errors due to hidden elements. 
NO TICKET
=> fix: table pagination layout

components/app/CRAEntryPoint.tsx, components/authentication/signup/constants/AuthConstants.ts, components/authentication/signup/formFields/AuthFormFields.tsx, package-lock.json, package.json
=> feat: update sign-up declaration wording

components/app/CRAEntryPoint.tsx, components/authentication/signup/constants/AuthConstants.ts, package.json
The last commit removed the validation trigger/msg (oops) so put it back. That will teach me for being smug. 😅
NO TICKET
=> fix: auth validation

cypress/e2e/formr-b/FormRB.spec.ts, package-lock.json, package.json
... so the MFA token refreshes in e2e Form B creation/checking submitted form steps.
NO TICKET
=> fix: wait time between MFA uses

components/common/ExpanderMsg.tsx, components/forms/form-builder/form-r/part-a/formA.json, cypress/support/commands.ts, mock-data/combinedReferenceData.ts, models/ProfileToFormRPartAInitialValues.ts, package-lock.json, package.json
- Default programmeMembershipType field to "Substantive"
- Add expander with definitions for "Military" and "Substantive" types 
TIS21-6049
=> Update programmeMembershipType field and add definitions

cypress/e2e/notifications/Notifications.spec.ts, package-lock.json, package.json
and reorder the intercept to see if that fixes the flaky test.
NO TICKET
=> chore: remove duplicate e2e test wait

cypress/support/commands.ts
=> test: update asserted validation message

components/dsp/CredentialIssue.tsx, components/dsp/CredentialVerify.tsx, components/dsp/DspIssueBtn.tsx, components/dsp/__test__/CredentialIssue.test.tsx, cypress/component/dsp/DspIssueBtn.cy.tsx, package-lock.json, package.json
=> feat update wording for dsp buttons

components/forms/form-builder/FormBuilder.tsx, cypress/e2e/formr-b/FormRB.spec.ts, package-lock.json, package.json, utilities/FormBuilderUtilities.ts
Disable shortcut btn when page errors.
NO TICKET
=> fix: shortcut btn bug

cypress/e2e/formr-b/FormRB.spec.ts, package-lock.json, package.json
...between form b tests to allow MFA refresh
(should have put it to 30s in the first place 😂)
NO TICKET
=> fix: e2e wait time increased

components/common/PanelsCreator.tsx, cypress/component/placements/Placements.cy.tsx, mock-data/trainee-profile.ts
@john12321 - look ok to you? Feels a bit clumsy, but that's 'fullstackers' for you 😁
=> fix: alphabeticise other specialties

components/forms/form-builder/FormBuilder.tsx, components/forms/form-builder/form-fields/Dates.tsx, components/forms/form-builder/form-r/part-a/formA.json, components/forms/form-builder/form-r/part-b/formB.json, components/forms/form-builder/form-r/part-b/formBValidationSchema.ts, cypress/support/commands.ts, package-lock.json, package.json, utilities/FormBuilderUtilities.ts, utilities/__test__/FormBuilderUtilities.test.ts
...with soft validation warning msg.
Was a bit more fiddly than expected because the function to display warning was expecting a regex. 
See [slack thread](https://hee-nhs-tis.slack.com/archives/G0135LS4JVA/p1718104244591819) for further details.
NO TICKET
=> feat: replace currRevalDate hard validation

components/app/CRAEntryPoint.tsx, components/common/AutocompleteSelect.tsx, components/common/ExpanderMsg.tsx, components/common/PanelsCreator.tsx, components/forms/cct/CalcForm.tsx, components/forms/cct/Cct.tsx, components/main/Main.tsx, components/programmes/CctBtn.tsx, cypress/component/forms/cct/Cct.cy.tsx, cypress/component/programmes/Programmes.cy.tsx, cypress/e2e/programmes/Programmes.spec.ts, package-lock.json, package.json, redux/slices/cctCalcSlice.ts, redux/slices/index.ts, styles/globals.scss, utilities/CctUtilities.ts, utilities/FormBuilderUtilities.ts, utilities/__test__/CctUtilities.test.ts, utilities/hooks/useIsMobile.ts
Add basic CCT form to calculate new end dates for single or multiple WTE changes (higher to lower WTE(s) and vice versa).
Allow user to add bespoke values for WTE percentages.
Add some agreed defaults and basic form validation.
Add some warnings for user to consider (e.g. change date < 16 weeks, bespoke WTE).
Allow CCT calc to remain active as user interacts with other parts of the app.
Fix CCT position on phone/small mobile to top of page; Make CCT draggable on other devices.
Add 'further info' as expander.
Set print preview for draggable dialog.
Target dialog element so only this shows in print preview (reset its position before preview so that it appears in the correct position for printing).
Note:
Test CCT calc functionality via browserstack using multiple devices before pushing to …
=> Feat: Add CCT Calculator to TSS

cypress/e2e/programmes/Programmes.spec.ts, package-lock.json, package.json
by slapping a conditional on it.
TIS21-6118
=> fix: Prog e2e

components/authentication/signup/header/AuthHeader.tsx, cypress/e2e/authenticator/Authenticator.spec.ts, package.json, styles/globals.scss
=> feat: July 2024 email issues notification

components/common/PanelsCreator.tsx, cypress/component/programmes/Programmes.cy.tsx, mock-data/trainee-profile.ts, models/ProgrammeMembership.ts, package-lock.json, package.json, utilities/Constants.ts
Display the name of the responsible officer for each of a trainee's programmes.
TIS21-5805
TIS21-5827
=> feat: add responsible officer to programme card

package.json, utilities/Constants.ts
=> chore: update support emails

components/authentication/signup/header/AuthHeader.tsx, cypress/e2e/authenticator/Authenticator.spec.ts, package.json, styles/globals.scss
=> chore: remove email support issue notice

cypress/e2e/formr-a/FormRA.spec.ts, cypress/support/commands.ts, cypress/support/index.d.ts, package-lock.json, package.json
Well that last 'fix' went well, didn't it? 💩
The only other 'fix' I can think of is to throw the kitchen sink at the 'submit new form' btn to try to counter any modal-related madness.
NO TICKET
=> fix: the 'fixed' test

cypress/e2e/formr-a/FormRA.spec.ts, cypress/support/commands.ts, cypress/support/index.d.ts, package-lock.json, package.json
Targeting the btn element didn't work so instead add some 'wait' cmds before the btn click to ensure it is loaded/ state is reset.
NO TICKET
=> fix: the fix to the power of fix

components/placements/Placements.tsx, components/programmes/Programmes.tsx, cypress/component/programmes/Programmes.cy.tsx, mock-data/trainee-profile.ts, models/IDateBoxed.ts, models/Placement.ts, models/ProgrammeMembership.ts, models/TraineeProfile.ts, utilities/DateUtilities.ts, utilities/ProfileUtilities.ts, utilities/__test__/ProfileUtilities.test.ts
=> feat: group programmes like placements

components/forms/form-builder/form-r/part-a/FormRPartA.tsx, components/forms/form-builder/form-r/part-b/FormRPartB.tsx, cypress/component/forms/formr-part-a/FormA.cy.tsx, cypress/component/forms/formr-part-b/FormB.cy.tsx, cypress/e2e/formr-b/FormRB.spec.ts, cypress/support/commands.ts, package.json
=> feat: add form R info

components/common/InfoTooltip.tsx, components/common/PanelsCreator.tsx, cypress/component/programmes/Programmes.cy.tsx, mock-data/trainee-profile.ts, package.json, styles/globals.scss
Info icon next to COJ label
Mouseover the icon will give information about COJ
TIS21-6487
TIS21-6538
=> feat: add COJ info

components/authentication/Auth.module.scss, components/authentication/signup/header/AuthHeader.tsx, cypress/e2e/authenticator/Authenticator.spec.ts, package-lock.json, package.json
... for Foundation/PH docs.
TIS21-6648
=> feat: Add temp auth alert message

utilities/FileUtilities.ts, utilities/__test__/FileUtilities.test.ts
Create a utility function to handle downloading a PDF, given a filename
and a function to get the PDF blob.
TIS21-6106
TIS21-6123
=> feat: download pdf from server

package-lock.json, package.json, utilities/FileUtilities.ts, utilities/__test__/FileUtilities.test.ts
(It's showing object Object atm.)
NO TICKET
=> refactor: show error message for pdf fail

components/navigation/TSSHeader.tsx, package-lock.json, package.json
... via some conditional snowfall.
TIS21-6781
=> fix: lack of Christmas spirit

cypress/e2e/programmes/Programmes.spec.ts, package.json
... on Programmes.spec
NO TICKET
=> chore: revert the test sign-in wait time

components/navigation/TSSHeader.tsx, package-lock.json, package.json
=> feat: remove snow 2024 😢

components/forms/cct/CctCalcCreate.tsx, mock-data/mock-cct-data.ts, mock-data/mock-ltft-data.ts, models/ProgrammeMembership.ts, package-lock.json, package.json, redux/slices/cctSlice.ts, redux/slices/ltftSlice.ts, utilities/__test__/LtftUtilities.test.ts, utilities/ltftUtilities.ts
=> Add designatedBodyCode to PM and include ChangeId in CCT and LTFT DTOs

components/forms/ltft/LtftFormView.tsx, cypress/component/forms/ltft/LtftFormView.cy.tsx, package.json
=> feat: save & exit button on LTFT View page

components/forms/form-builder/form-sections/ImportantText.tsx, cypress/component/forms/ltft/LtftForm.cy.tsx, package.json
=> fix: LTFT form text

components/forms/ltft/LtftFormView.tsx, components/forms/ltft/LtftNameModal.tsx, components/forms/ltft/__test__/LtftNameModal.test.tsx, package.json, redux/slices/ltftSlice.ts, services/FormsService.ts, utilities/FormBuilderUtilities.ts, utilities/__test__/FormBuilderUtilities.test.ts
- Add submitLtft POST/PUT to` FormsService.ts`
- Add logic to `LtftNameModal.tsx` to add `name` to `formData`.
- Refactor `prepLtftData` util to set all declarations to `true` on submit
[TIS21-7118](https://hee-tis.atlassian.net/browse/TIS21-7118)
[TIS21-7118]: https://hee-tis.atlassian.net/browse/TIS21-7118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TSS - Submit LTFT

components/authentication/setMfa/sms/ConfirmSms.tsx, components/common/ActionModal.tsx, components/forms/MobilePhoneInputField.tsx, components/forms/MultiChoiceInputField.tsx, components/forms/SelectInputField.tsx, components/forms/TextInputField.tsx, components/forms/cct/CctCalcSummary.tsx, components/forms/form-builder/FormContext.tsx, cypress/component/authentication/CreateSms.cy.tsx, cypress/component/forms/cct/CctCalcView.cy.tsx, cypress/component/forms/ltft/LtftHome.cy.tsx, package-lock.json, package.json, utilities/FileUtilities.ts, utilities/FormBuilderUtilities.ts
**As discussed**
fix: remove charCount and maxLength for TextArea
**And**
fix: set sms code input to 6 digits in ConfirmSms component.
NO TICKET
feat: Add indicative completion (CCT) date warning on calc summary.
[TIS21-7165](https://hee-tis.atlassian.net/browse/TIS21-7165)
[TIS21-7165]: https://hee-tis.atlassian.net/browse/TIS21-7165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove charCount and maxLength for TextArea

components/forms/form-builder/FormBuilder.tsx, components/forms/ltft/LtftFormView.tsx, cypress/component/forms/ltft/LtftFormView.cy.tsx, mock-data/mock-ltft-data.ts, package.json
TIS21-6706
TIS21-7146
TIS21-7147
=> fix: buttons for unsubmitted Ltft view

components/forms/cct/CctSavedDraftsTable.tsx, components/forms/ltft/LtftFormView.tsx, components/forms/ltft/LtftHome.tsx, components/forms/ltft/LtftSummary.tsx, components/notifications/NotificationsTable.tsx, cypress/component/forms/ltft/LtftFormView.cy.tsx, cypress/component/forms/ltft/LtftHome.cy.tsx, cypress/component/forms/ltft/LtftSummary.cy.tsx, mock-data/mock-ltft-data.ts, package-lock.json, package.json, redux/slices/ltftSlice.ts, redux/slices/ltftSummaryListSlice.ts, styles/globals.scss, utilities/ltftUtilities.ts
- Add formRef to summary table and form view (submitted) summary data.
- Fix table layout 
- Style CCT table button the same as LTFT summary table 
[TIS21-7109](https://hee-tis.atlassian.net/browse/TIS21-7109)
[TIS21-7109]: https://hee-tis.atlassian.net/browse/TIS21-7109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat/add form ref 

components/forms/ltft/ltft.json, cypress/component/forms/ltft/LtftForm.cy.tsx, cypress/component/forms/ltft/LtftFormView.cy.tsx, mock-data/mock-ltft-data.ts, package-lock.json, package.json, redux/slices/ltftSlice.ts, utilities/__test__/LtftUtilities.test.ts, utilities/ltftUtilities.ts
[TIS21-7157](https://hee-tis.atlassian.net/browse/TIS21-7157)
[TIS21-7157]: https://hee-tis.atlassian.net/browse/TIS21-7157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
TODO:
[Update the warning wording](https://hee-tis.atlassian.net/browse/TIS21-7164) in next commit
=> feat: add supportingInformation field to LTFT form

components/forms/ltft/LtftSummary.tsx, cypress/component/forms/ltft/LtftHome.cy.tsx, cypress/component/forms/ltft/LtftSummary.cy.tsx, mock-data/mock-ltft-data.ts, package.json, redux/slices/ltftSummaryListSlice.ts
New Column to show unsubmit reason in table
TIS21-6706
TIS21-7143
Show application is unsubmitted by LO in status column
TIS21-6706
TIS21-7144
=> feat: add unsubmitted reason and modified by Role to LTFT Summary table

components/authentication/signup/formFields/AuthFormFields.tsx, components/authentication/signup/header/AuthHeader.tsx, cypress/e2e/authenticator/Authenticator.spec.ts, package-lock.json, package.json
...and update HEE email placeholder text.
JFDI
=> refactor: remove login warning

package-lock.json, package.json, utilities/Constants.tsx
[TIS21-7212](https://hee-tis.atlassian.net/browse/TIS21-7212)
[TIS21-7212]: https://hee-tis.atlassian.net/browse/TIS21-7212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update NE support email

components/forms/ltft/LtftFormView.tsx, package-lock.json, package.json, pages/_app.tsx, types.d.ts
... for Hotjar integration.
(GA tag instructions are on https://analytics.google.com/analytics/web/#/a40570867p373187423/admin/streams/table/5142383092 )
chore: Add `gtag` event to `LtftFormView.tsx handleModalFormSubmit` function. This should allow us to first capture the submission event in GA. We should then be able to use this GA event in Hotjar to create a Hotjar event to trigger a survey.
Note: No GA admin access (yet) so can't create a preprod GA data stream to test stuff on.
TIS21-7281
=> chore: update GA scripts

components/forms/form-builder/form-sections/ImportantText.tsx, package.json
=> fix: update Form R Part B TOOT guideline text

components/forms/form-builder/form-r/part-b/formB.json, components/forms/form-builder/form-sections/ImportantText.tsx, package-lock.json, package.json, utilities/Constants.tsx
=> refactor: remove mentions of RITA from form r

components/forms/form-builder/FormView.tsx, package-lock.json, package.json
Correctly (re-)link programmeSpecialty even if it is blank up to this point.
NO TICKET
=> fix: relink programmeSpecialty before submission

cypress/component/support/Support.cy.tsx, package.json, utilities/Constants.tsx
=> fix: add Changing hours (LTFT) and remove DSP from Support Category

components/home/Home.tsx, components/profile/Profile.tsx, components/profile/ProfilePage.tsx, cypress/e2e/authenticator/Authenticator.spec.ts, package-lock.json, package.json
=> fix: auth e2e test

components/main/Main.tsx, components/main/__test__/Main.test.tsx, package-lock.json, package.json
.. when user signs in with SMS as preferred MFA method.
[TIS21-7506](https://hee-tis.atlassian.net/browse/TIS21-7506)
[TIS21-7506]: https://hee-tis.atlassian.net/browse/TIS21-7506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: redirect to MFA page

components/common/ExpanderMsg.tsx, components/forms/cct/CctCalcCreate.tsx, cypress/support/commands.ts, package-lock.json, package.json
=> refactor: add skilled visa expander to CCT calculator

components/programmes/TrainingNumber.tsx, cypress/component/programmes/TrainingNumber.cy.tsx, package-lock.json, package.json
**Problem**
NTN not being displayed due to FormR trainee-action logic not being aligned to new API logic for trainee-actions.
**"Fix"**
As a quick fix to let a user see their NTN, delete the FE FormR logic used to conditionally display the NTN. 
Will fix properly in a follow-up commit.
NO TICKET
=> fix: NTN not being displayed even when users have submitted Form Rs

.github/workflows/pr-analysis.yml, components/forms/SubmittedFormsList.tsx, cypress/e2e/formr-a/FormRA.spec.ts, cypress/e2e/formr-b/FormRB.spec.ts, package.json
As per the comment from Admin, we are suggested to change the Form R table from `Previous applications` to `Submitted forms`.
=> fix: change submitted Form R table header

components/main/GlobalAlert.tsx, cypress/e2e/home/Home.spec.ts, package-lock.json, package.json
add correct link and update test to take into account that ActionLink is used now
NO-TICKET
=> fix: broken link and e2e test

components/forms/cct/__test__/RowCctActions.test.tsx, mock-data/trainee-profile.ts, models/FeatureFlags.ts, package-lock.json, package.json, redux/slices/userSlice.ts, utilities/hooks/useIsLtftPilot.ts, utilities/ltftUtilities.ts
The UserFeatures data structure has changed to a more granular structure. Update the UserFeatures type and refactor usage of the LTFT flags.
TIS21-7657
TIS21-7661
=> refactor: feature flag structure
