Health-Education-England/tis-trainee-ui

src/services/ProfileService.ts
The endpoint used in ProfileService does not exist and should call
trainee-profile instead.
TISNEW-3946
=> fix: Incorrect endpoint called from ProfileService

package-lock.json, package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/forms/InputFooterLabel.tsx, src/components/forms/SelectInputField.tsx, src/components/forms/TextInputField.tsx, src/components/forms/__test__/InputFootereLabel.text.tsx, src/components/forms/__test__/SelectInputField.test.tsx, src/components/forms/__test__/TextInputField.test.tsx, src/components/forms/formr-part-a/Create.tsx, src/components/forms/formr-part-b/Sections/Section1.tsx
TISNEW-4531
- Modified the existing components **TextInputField** and **SelectInputField** to include components from the NHS React library that support inline error messaging and hint text. https://nhsdigital.github.io/nhsuk-react-components/?path=/story/input--with-error-string
- Added option to render multi-line html textarea instead of input field by setting a rows property   
- Updated error summary in line with NHS React component to improve accessibility through improved labelling.
- Added new component, **InputFooterLabel** to allow insertion of additional text below the form field that supports html markup to allow for inclusion of links.
- Added missing label properties to the address form fields on formr part a.
- Added hint text to email form field on formr part b, advising on …
=> feat: Added inline error messaging for text and select input components

cypress/integration/formr-a/formr-a.spec.ts, cypress/support/commands.js, src/components/forms/SelectInputField.tsx, src/components/forms/StringValidationSchema.ts, src/components/forms/formr-part-a/Create.tsx, src/components/forms/formr-part-b/Sections/CovidDeclaration.tsx, src/components/forms/formr-part-b/Sections/FormRPartBPagination.tsx, src/components/forms/formr-part-b/Sections/Section3.tsx, src/components/forms/formr-part-b/Sections/Section4.tsx, src/components/forms/formr-part-b/Sections/Section5.tsx, src/components/forms/formr-part-b/ValidationSchema.ts, src/components/forms/formr-part-b/View.tsx, src/components/forms/formr-part-b/__test__/Confirm.test.tsx, src/components/forms/formr-part-b/__test__/CovidDeclaration.test.tsx, src/components/forms/formr-part-b/__test__/FormRPartBPagination.test.tsx, src/models/FormRPartB.ts, src/services/TraineeReferenceService.ts
- Add COVID declaration form sections 3 & 4
- Fix form validation bug where validation lags behind change event (e.g. validation msg remained after field checked)
- Fix bug in COVID section and other sections so change event which hides a field also resets its value and therefore stops data persisting and being saved to db)
TICKET: TISNEW-4946
=> Add sections 3 & 4 to COVID Declaration form

package.json, src/services/apiService.ts
API Gateway only supports authentication using identity tokens out of
the box, use `idToken` instead of `accessToken` so the API can be called
when secured.
At a later date the token should be switched back to the access token
once configuration can be done to use it.
TISNEW-4307
=> fix: Call the API with identity token

package.json, src/services/apiService.ts
The dummy data trainee ID needs changing so that real data does not get
synchronized in to the application. The new ID matches a dummy trainee
that we have permission to use.
TISNEW-5154
=> fix: Use new dummy trainee ID

package.json, src/components/forms/formr-part-b/Sections/CovidDeclaration.tsx, src/components/forms/formr-part-b/ValidationSchema.ts, src/components/forms/formr-part-b/View.tsx
- Make additional mandatory text field only appear when options 1 or 2 selected
- Make text field at the end of the section 1 non-mandatory - with a word limit of 1000 characters
- Minor version bump
TISNEW-5243
=> Redesign Covid Form - Section1

cypress/support/commands.js, package-lock.json, package.json, src/services/FormsService.ts, src/services/TraineeProfileService.ts, src/services/TraineeReferenceService.ts, src/services/apiService.ts
A new set of API endpoints has been created with a shared `/api` parent
instead of individual `/api` children. Migrate to use the new endpoints,
which also no longer need the trainee's TIS ID to be provided.
TISNEW-3833
=> refactor: Migrate api service to new API endpoints

package.json, src/components/profile/personal-details/PersonalDetailsComponent.tsx
The error message displayed when no trainee data is available in the
trainee profile is incorrectly spelt.
NO-TICKET
=> fix: Type in trainee profile error message

.github/workflows/analyze-with-sonarqube.yml
**Problem**
- Build warning that the 'add-path' command is deprecated and will be disabled on 16/11/2020 
- Build SonarCloud scan: _WARN You are using Node.js version 8, which reached end-of-life. Support for this version will be dropped in future release, please upgrade Node.js to more recent version._
**Solution**
Update actions/setup-node to v1.4.4
TISNEW-5709
=> Update actions/setup-node to v1.4.4

.github/workflows/analyze-with-sonarqube.yml
Input 'version' property has been deprecated. Need to use 'node-version' property.
TISNEW-5709
=> fix: node version syntax

package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/profile/placements/PlacementPanel.tsx, src/components/profile/placements/Placements.tsx, src/mock-data/trainee-profile.ts, src/models/Placement.ts
Add `employingBody`, `trainingBody`, `wholeTimeEquivlent` and
`siteLocation` fields to the placement panel.
Update the placements to be displayed as halves instead of thirds as the
new data becomes too cramped with thirds.
TIS21-1032
=> fix: Add missing placement fields

package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/mock-data/trainee-profile.ts, src/models/Placement.ts
The `placementTisId` field was renamed to `tisId` in the backend and
needs updating here.
TIS21-1032
=> fix: Rename placementTisId field

.github/workflows/deploy.yml
The E2E task in the deploy action included a continue-on-error flag so fails were not showing in GitHub. This flag has been removed and additional conditionals have been added to make sure the artifacts are still generated and backed-up and Slack message sent. The Slack messaging has been separated for success and failures and styled accordingly.  
NO TICKET
=> fix: so e2e task shows as failed in github

cypress/integration/formr-a/formr-a.spec.ts, cypress/support/commands.js
Immigration status of other is no longer required so test removed from E2E. This status will need to be removed from the code and the field otherImmigrationStatus removed from data model. However, leaving this does not impact the application and in the spirit of E2EDD, wanted to commit this change first so tests pass and refactor code later.
=> test:remove other immigration status test

.github/workflows/deploy.yml
E2E tests were failing due to running against a version of Chrome that was greater than 3 versions behind the current, resulting in the banner being displayed and concealing some inputs. The container `cypress/browser:latest` appears not to be latest having been updated 5 months ago and runs Chrome 83 so I have set this as a the actual latest container tag. Going forward, I don't think we should rewrite the tests to accommodate the presence of the banner since we don't support that browser version, but we will need to update the container tag periodically as the version of chrome is updated, or find an alternative approach.
=> fix:update container to defined tag

package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/mock-data/trainee-profile.ts, src/models/ProfileToFormRPartAInitialValues.ts, src/models/ProfileToFormRPartBInitialValues.ts, src/models/__test__/ProfileToFormRPartAInitialValues.test.ts, src/models/__test__/ProfileToFormRPartBInitialValues.test.ts
When the trainee's latest programme had no medical curriculums the
FormA/B failed to load, due to a TypeError on the `reduce()` function
called on the empty array.
Perform a sort instead of reduce to get the latest curriculum as it
better handles the empty array.
TIS21-1327
=> fix: error when non medical curriculum

package-lock.json, package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/authentication/Login.tsx
**Problem**
As of aws-amplify-react@4, the Authenticator is not styled
Solution
Manually import default css to provide a base for our custom css changes.
NOTE: The next step (new tech improvement ticket) will be to replace **aws-amplify-react** (legacy) with **@aws-amplify/ui-react** (although from a brief look at the new library, the API doesn't look to be as user-friendly)
TIS21-1445
=> fix: Breaking change after updating aws-amplify-react from 3 to 4

cypress/integration/profile/profile.spec.ts, package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/profile/personal-details/PersonalDetailsComponent.tsx
- Rename the Sensitive data heading to Registration details. 
- Instead of GMC, GDC, PH, to have the full label or registration bodies visible to make the fields more explicit.
TIS21-1348
=> Change Sensitive data heading and labels

package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/authentication/Login.tsx
- Add SMS MFA support to existing version of amplify UI components
- SMS MFA must be enabled for each user in relevant Cognito user pool assuming pool has MFA set to optional
- Phone number must be verified. If not, the confirm box is displayed and SMS message is sent but authentication will fail.
- Users without SMS MFA enabled will be able to login as before.
https://hee-tis.atlassian.net/browse/TIS21-1459
=> feat:add confirm signin component

.github/workflows/deploy.yml
The build docker image should be tagged with `latest` as well as the
commit sha.
TIS21-1460
=> chore: Tag the docker image with `latest`

package.json, src/__snapshots__/App.snapshot.spec.tsx.snap
This should get rid of sharedArrayBuffer cross-origin console warning
https://github.com/facebook/react/issues/20829
TIS21-1527
=> chore: Bump react and react-dom

package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/index.tsx
**Problem**
Console error `Error during service worker registration: DOMException: Failed to register a ServiceWorker for scope ('https://trainee.tis-selfservice.nhs.uk/') with script ('https://trainee.tis-selfservice.nhs.uk/service-worker.js'): The script has an unsupported MIME type ('text/html')` when the preprod and prod versions run - following a recent CRA (create-react-app) upgrade.
**Quick fix(es)**
Given we're not deploying a PWA at present, there is no need to register a service worker.
- unregister service worker
(if this doesn't fix the error then we can delete the serviceWorker.ts file and related files in index.ts) 
**Longer-term fix**
If we do plan to develop a PWA then this error relating to service worker registration needs to be fixed. Latest suggestions involve moving …
=> Unregister sw

package.json, public/index.html, src/__snapshots__/App.snapshot.spec.tsx.snap
- Although TISSS has been developed for evergreen browsers, loading the app on IE11 displays a blank screen due to errors caused by unsupported scripts. With IE still present within NHS organisations and in some cases the default browser, a fix is required to display a message to users explaining that the browser is unsupported. 
- Since IE11 is no longer supported by MS (and it's a pile of poo), a quick fix approach was preferred, adding a basic message into the static index.html that is conditionally displayed when accessed via IE. 
- `document.documentMode` property is only supported by IE hence why its used to determine the browser.
=> fix:add IE specific message to index.html

package.json, public/index.html, src/__snapshots__/App.snapshot.spec.tsx.snap
Add Google Analytics 4 tagging in parallel with GA3 tagging. SPA page routes are tagged with GA4 but not in GA3 without Google Tag Manager. With the pilot starting 24 May, wanted to get tagging of page routes enabled.
=> feat:add GA4 tag

package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/index.tsx
Add Google tag manager via npm package to collect custom event data for pilot.
=> feat:add GTM for improved event tagging

.github/workflows/analyze-with-sonarqube.yml
Reverts Health-Education-England/tis-trainee-ui#449
Getting cypress error which needs further investigation:
1) Form R (Part A)
Should complete a new Form R Part A.:
CypressError: `cy.select()` can only be called on a `<select>`. Your subject is a: `<input class="nhsuk-input nhsuk-input--width-20" aria-labelledby="qualification--label" name="qualification" id="qualification" formik="[object Object]" min="1920-01-01" max="2119-31-12" data-cy="qualification" type="text" value="Degree">`
=> Revert "chore(deps): bump SonarSource/sonarcloud-github-action from 1.4 to 1.6"

cypress/integration/formr-a/formr-a.spec.ts, cypress/support/commands.js
This fix is in prep for dependabot update https://github.com/Health-Education-England/tis-trainee-ui/pull/469. This PR was previously merged and subsequently reverted following the failure of E2E tests.
Previously, the organisation field was a dropdown. E2E tests hadn't been updated following changing this to free text so were still using select() method. These tests now fail following an update to the latest version of sonarcloud.
=> fix:update organisation removing select references

package-lock.json, package.json, src/__snapshots__/App.snapshot.spec.tsx.snap
**Problem** 
Previous build failed to compile: `Cannot find module '@cypress/react'`.
This has happened before when the library is in the dev dependencies but is required in dependencies (package.json) for Dockerize build.
**Solution**
Move cypress libraries from dev deps to deps to fix build compilation error.
=> fix: Move updated Cypress libraries from dev deps

cypress/integration/formr-a/formr-a.spec.ts, cypress/integration/formr-b/formr-b.spec.ts, package-lock.json, package.json, src/__snapshots__/App.snapshot.spec.tsx.snap
Cypress.moment is now deprecated so using Dayjs instead.
Moment is on its way out so next step is to remove it completely and replace with Dayjs.
=> fix: e2e test

cypress/integration/formr-b/formr-b.spec.ts, package.json, src/__snapshots__/App.snapshot.spec.tsx.snap
Since Cypress update 7.3.0 there is a failing test where - under certain conditions - toggling a checkbox does not display the error message. 
It is a bit of a mystery why this test has only started failing now but it has done its job in uncovering what looks like a bug with the Formik/Yup validation. 
A bug ticket will be created after this merge to work on resolving this bug and uncommenting the failing test.
=> test: Temp remove failing test

cypress/integration/formr-b/formr-b.spec.ts, package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/forms/MultiChoiceInputField.tsx
**Problem**
A bug recently surfaced whereby toggling a checkbox in Form R Part B (Section 7) will not always show the validation error message when the checkbox is unchecked. It works fine in Section 3 where other fields are present. 
**Solution**
Tweak the onChange event in the MultiChoiceInputField component to make sure the error message is always displayed when a Checkbox is unchecked.
TIS21-1743
=> fix: Checkbox bug

src/components/authentication/SetTOTP.tsx
Updated instruction text removing reference to the browser-based authenticator GAuth, due to security concerns.
=> fix:update user guide text

.eslintrc, cypress/support/commands.js, package.json, src/__snapshots__/App.snapshot.spec.tsx.snap, src/components/forms/formr-part-b/Create.tsx, src/components/forms/formr-part-b/Sections/Section1.tsx
This is the first iteration to allow the user to select 'other' when their
previous Designated Body is non-Deanery. Next steps include allowing the user
to choose from a list of non-Deanery designated bodies after they select 'other'.
TIS21-1838
=> feat: Add 'other' option to prevRevalBody options

package.json
Update jest configuration to exclude the cypress integrations tests from code coverage. Reordered the rules as need to set include rules first before the exclude rules.
=> fix:update coverage rules

package.json, src/components/authentication/LoginNew.tsx
- Currently, when a user has TOTP on their device, the issuer name on their authenticator app is AWSCognito
- The new name is Trainee Self-Service
=> Change issuer name on auth app

package.json, src/components/authentication/LoginNew.tsx
- Add more support text to TOTP setup screen
- Remove the generic TIS Support link from TOTP setup page (but leave on sign in page)
TODO
- Need to configure some more Cypress tests for sign in/TOTP screens for a test user who has not already set up TOTP but don't want to hold up these relatively minor changes for this today.  
NO TICKET
=> feat: Add more TOTP support text

package.json, src/components/forms/MultiChoiceInputField.tsx
When there are multiple checkboxes in a single panel clicking on the text for any of the checkboxes selects the first box, instead of the box belonging to the label you clicked. 
TIS21-2455
=> remove '|| "item_" + index' which points to the wrong checkbox

.aws/task-definition-pre-prod.json, .github/workflows/deploy.yml
Rename the preprod container to match the current naming standards.
TIS21-2560
=> chore: rename preprod container to meet standards

cypress/integration/formr-b/formr-b.spec.ts, package.json, src/components/forms/formr-part-b/sections/Section2.tsx
**Problem** 
The recent state management upgrade work has led to a bug where the totalLeave form field (Form R Part B - TOOT section) shows the correct value in the UI but is not being saved. This has knock-on effects for Admins UI and Metabase reports where the totalLeave is incorrectly shown as zero.
**Solution** 
Fix the form logic to create a new form values object before save/ submission actions.
TICKET TIS21-2791
=> Fix Form R Part B TOOT bug

cypress/integration/formr-a/formr-a.spec.ts, package.json, src/components/forms/formr-part-a/ValidationSchema.ts, src/utilities/Constants.ts
- Remove regex that validates UK postcode
- Limit field to 20 chars, keep 'required' validation too.
TICKET TIS21-2909
=> fix: remove UK postcode validation blocker

cypress/integration/formr-b/formr-b.spec.ts, package.json, src/components/forms/formr-part-b/View.tsx, src/components/forms/formr-part-b/sections/Section2.tsx, src/mock-data/draft-formr-partb.ts, src/utilities/ProfileUtilities.ts, src/utilities/__test__/ProfileUtilities.test.ts
**Problem** (via TSS user feedback)
- Work placements loaded (i.e. those synced from TIS) are sorted by end date (desc) when Form R (B) Section 2 loads.
- But any additional work placements entered by the user are just added to the end of the list without being sorted.
**Solution**
- Work placements sort is now triggered on ‘save’ draft and navigation to another section.
TICKET TIS21-2906
=> Feat/sort Type of Work placements (desc)

package.json, src/components/profile/Profile.cy-test.tsx, src/mock-data/trainee-profile.ts, src/models/ProfileToFormRPartBInitialValues.ts, src/utilities/ProfileUtilities.ts, src/utilities/__test__/ProfileUtilities.test.ts
In response to user feedback:
- Set Work Training Post inital vals to 'Yes' for any type including 'In Post'
- For now, set all others to null so user still has to decide.
TICKET TIS21-1341
=> feat: Set Work Training Post inital vals to YES for In Post

package-lock.json, package.json
Some GitHub issues report earlier versions not showing out-of-date browser banner for Safari 14. (e.g. https://github.com/browser-update/browser-update/issues/548) 
NO TICKET
=> chore: bump browser-update

cypress/integration/mfa/mfa.spec.ts, package.json, src/components/authentication/setMfa/ChooseMfa.tsx, src/components/authentication/setMfa/MFA.scss, src/components/authentication/setMfa/sms/ConfirmSms.tsx, src/components/authentication/setMfa/sms/VerifySms.tsx, src/components/authentication/setMfa/totp/TotpInstructions.tsx, src/components/authentication/setMfa/totp/VerifyTotp.tsx, src/components/forms/MobilePhoneInputField.scss, src/components/forms/MobilePhoneInputField.tsx, src/models/MFAStatus.ts, src/redux/slices/notificationsSlice.ts, src/redux/slices/userSlice.ts
- Remove phone_number attribute when swapping MFA type from SMS to TOTP.
- Order the actions so the phone_number removal is the last action in TOTP set-up process just in case process is aborted.
- Refactor some mfa comps
TODO 
- (see https://github.com/Health-Education-England/tis-trainee-ui/pull/680 )
- refactor redux slices to make DRY
- look at ways to increase test coverage for sign-up/MFA 
TICKET TIS21-3193
=> Remove phone_number attribute when swapping MFA type from SMS to TOTP

package.json, src/components/support/Support.cy-test.tsx, src/components/support/Support.tsx, src/components/support/SupportList.tsx, src/mock-data/trainee-profile.ts
Following feedback at last TSS meeting where support staff are finding it difficult to locate users' details (which could lead to cases of mistaken ID/ possible data breaches):
- Add GMC (when given) and tisId to subject of support emails
TICKET TIS21-3246
=> feat: Add gmc and/or tisId to support emails

Dockerfile, package.json
- node v12 end-of-life so upped build version to v14
NO TICKET
=> Update dockerfile node

package-lock.json, package.json, src/components/forms/formr-part-a/ValidationSchema.ts, src/components/forms/formr-part-b/ValidationSchema.ts
The surname field is too restrictive at 30 characters, pre-populated
data from TIS can trigger the field validation as TIS allows up to 255
characters.
Remove the 30 character limit.
TIS21-3299
=> fix: remove 30 character limit on surname

cypress/integration/profile/profile.spec.ts, package.json
as temporary solution to unblock GHA pipeline
due to "not.be.visible" Cypress test failure running on new Chrome
=> test: comment out expender visible assertion

.github/workflows/deploy.yml
Not sure if this is really needed, (or if it'll work ...) but it may be good to see how it goes running the e2e tests on different browsers, this PR will set cypress to use electron, chrome and firefox, but if chrome or firefox crash and electron complete successfully then it will just continue to the next step of the deploy pipeline, only if electron fails its tests then we fail that job.
🤞🏻
=> ##### DRAFT ###### run a matrix of tests using electron, chrome and firefox

cypress/integration/authenticator/authenticator.spec.ts, cypress/integration/footer/footer.spec.ts, cypress/integration/formr-a/formr-a.spec.ts, cypress/integration/formr-b/formr-b.spec.ts, cypress/integration/mfa/mfa.spec.ts, cypress/integration/navbar/navbar.spec.ts, cypress/integration/profile/profile.spec.ts, cypress/integration/support/support.spec.ts
The app is returning `404` errors when using routes to navigate directly to a view e.g. `<base-url>/profile`, this is an infrastructure limitation and the response body is still the full working application. Update the Cypress tests to no longer fail based on the status code when navigating directly to a specific view. Use the base url wherever appropriate to reduce the number of places we need to ignore the status code.
TIS21-3726
=> test: do not immediately fail tests on 404

.github/workflows/deploy.yml
The workflow fails when running parallel tests for unknown reasons. Exclude the firefox and electron tests until they can be looked at again.
TIS21-3726
TIS21-3727
=> chore: exclude experimental browser tests

.github/workflows/deploy.yml
The static JS and CSS content is cached within Cloudfront, when deploying a new version of the site that cache should be invalidated. Technically this is not required for normal running of the application, as the CSS an JS files are versioned with a content hash. While Cloudfront does not need to re-cache a file with the same name, invalidating the cache does mean that old un-used version are cleaned up more quickly.
TIS21-3765
TIS21-3781
=> chore: invalidate cloudfront cache on deploy

package-lock.json, package.json, src/redux/slices/traineeProfileSlice.ts, src/services/__test__/apiService.test.ts, src/services/apiService.ts
TODO: tests
Example sentry alert triggered by 401 on GET trainee/profile: https://sentry.io/organizations/health-education-england-9v/issues/3781050571/?environment=development&project=1882746&query=&referrer=issue-stream&sort=date&statsPeriod=1h
TIS21-3746
=> Feat: sentry alert for failed API calls

cypress/integration/formr-a/formr-a.spec.ts, cypress/integration/formr-b/formr-b.spec.ts
Quick and dirty/ !DRY fix (will add the conditional as a cypress cmd when Next JS migration is done). 
Conditional solves the problem where the test will break if no recently-submitted forms (following the great purge).
NO TICKET
=> fix: breaking cypress e2e tests

cypress/integration/formr-a/formr-a.spec.ts, cypress/integration/formr-b/formr-b.spec.ts
Add another conditional in Form-r b test (missed in the last fix) to check for the MUI pop-up msg again after navigating away from the form page. In Form-r a, populate the programmeSpecialty field (looks like the preprod data has changed so no pre-pop programmeSpecialty) so there's no form error before submission.
NO TICKET (but epic potential)
=> fix: e2e tests again

src/components/profile/Profile.cy-test.tsx, src/components/profile/Profile.tsx, src/mock-data/trainee-profile.ts
The profile panel creator uses `Object.assign(a, b)` to populate the placement and programme membership templates with data. However, that also brings all remaining properties from object `b` resulting in unexpected field values appearing.
Update Profile.tsx to populate only properties that exist in the template object.
TIS21-3681
TIS21-3692
=> fix: only show templated fields on profile panels

.github/workflows/deploy.yml
Artefacts are only backed up if the E2E tests pass, this should always be done.
TIS21-SHED
=> build: always backup artifacts

components/common/Loading.tsx, components/dsp/CredentialIssue.tsx, components/dsp/CredentialIssued.tsx, components/dsp/CredentialVerify.tsx, components/dsp/DSPPanel.tsx, components/dsp/DspIssueBtn.tsx, cypress/component/dsp/CredentialIssue.cy.tsx, cypress/component/dsp/CredentialIssued.cy.tsx, cypress/component/dsp/CredentialVerify.cy.tsx, cypress/support/commands.tsx, cypress/support/index.d.ts, package.json, redux/slices/dspSlice.ts
Add more Cypress CT's to cover the main happy paths (i.e. the various screens on the issue -> verify -> issue journey) .
TODO: There are more conditions to test and also the onClick events but this can probably wait until we finalise the unhappy paths, feature flags etc.
(ps. There's a bit of refactoring to do to make the test files a bit DRY'er which can wait for the next PR 😩 )
NO TICKET
=> Add more DSP Credential CT's

.github/workflows/pr-analysis.yml
The folder structure was changed and no longer has everything under a `src` folder. Update the regex to include source folders.
This is a quick fix, a better approach may need to be considered now we don't have the common `src` parent folder.
TIS21-SHED
=> chore: update analysed folders

services/TraineeProfileService.ts, services/__test__/TraineeProfileService.test.ts, services/apiService.ts, utilities/__test__/CojUtilities.test.ts
The `TraineeProfileService.signCoj()` function passes `null` for the POST request body, but that is not allowed.
Update the `ApiService` to allow the POST request form data to be optional.
TIS21-4389
TIS21-4374
=> fix: signCoj service function passing null body

components/main/GlobalAlert.tsx, package-lock.json, package.json
Wrap the alerts object in a useMemo hook to prevent unnecessary re-renders. At the moment, it makes the dependencies of the useEffect change on every render - which is not good for performance. It will now only be re-evaluated when the showCojAlert value changes.
JFDI
=> fix: alerts object

.github/workflows/pr-analysis.yml
The `jitterbit/get-changed-files` action is outdated and no longer appears to be maintained. It will shortly stop working when Node 12 and `set-output` commands are deprecated.
Replace it with the `Ana06/get-changed-files` fork, which has resolved these issues.
TIS21-4561
=> build: handle GHA deprecation

components/programmes/ConditionsOfJoining.tsx, cypress/component/programmes/ConditionsOfJoining.cy.tsx, package-lock.json, package.json
The COJ actions are currently a button, but should be styled as links instead.
Swap the `button` element for `Link`s and refactor the `viewCoj` function in to `setCojState` with the navigation done within the link itself.
Update the ConditionOfJoining component tests to wrap the component in a `BrowserRouter` so that the `Link`s can work during testing.
TIS21-4544
TIS21-4533
=> refactor: style COJ actions as links

components/forms/form-builder/FormBuilder.tsx, cypress/component/forms/formr-part-a/FormA.cy.tsx, cypress/e2e/formr-a/FormRA.spec.ts, cypress/e2e/formr-b/FormRB.spec.ts, package.json
The last merge did reset the JSON form fields to their defaults when navigating away from the form but had numerous unintended consequences 💥 . This commit fixes those issues and brings the formBuilder back to the state before the "fix". 
The Cypress tests have also been updated to:
1. remove the otherImmigrationStatus test from FormRA as the "other" immigration options are not on prod.
2. Update the formsList btn text in FormRB
TODO
1. Fix the bug (without breaking everything else) where fields made visible by a conditional are not reset when navigating away from the form.
=> fix: the form states

components/forms/FormsListBtn.tsx, components/forms/form-builder/FormBuilder.tsx, cypress/e2e/formr-a/FormRA.spec.ts, package.json
Fixed (hopefully without breaking anything else) bugs:
1. JSON form fields' visibility were not reset when navigating away then opening a new form. This was fixed by not directly mutuating the (JSON forms) fields.
2. When completing a form and making a dependent field visible via a click event on the parent (e.g. programme specialty radio click unhides the 2 cct fields), these fields should remain visible and therefore subject to validation. However, a bug meant that these dependent fields' visibility was reset to the default hidden when the saved draft form was reopened so the validation did not fire when navigating to the next page. This was fixed by Initialising the dependent (JSON form) fields' visibility based on their parent field's (fetchedFormData) value/state.
TODO: Added  an e2e …
=> fix: 2 formBuilder bugs

components/home/TssUpdates.tsx, cypress/component/home/TssUpdates.cy.tsx, package-lock.json, package.json, styles/globals.scss
Given that we're sticking to the AC's 😁 and only showing the latest 'what's new' post, we can ditch some useless TS / CSS.
Also tidied up the styling for when there is no post to show.
NO TICKET
=> Chore/remove redundant what's new code

.github/workflows/deploy.yml
Deploy the app to a versioned directory in parallel to the existing deployment, this ensures correct working before implementing the cloudfront changes.
TIS21-4852
TIS21-3784
=> build: deploy to versioned directory in parallel

.github/workflows/deploy.yml
When a versioned deploy is complete, update the cloudfront origin path to point to the new deploy folder.
Remove the cache invalidation step, as it is automatically performed when switching origin paths.
TIS21-3784
TIS21-4852
TIS21-4853
=> build: update cloudfront origin path on deploy

.github/workflows/deploy.yml
The prod deployment step was incorrectly deploying to the preprod bucket, update the deploy command to publish to the correct bucket.
TIS21-3784
=> build: deploy prod to correct bucket

cypress/e2e/formr-a/FormRA.spec.ts
Sorry, missed this one. There were other e2e tests that only failed after the original PR was merged, but I'm assuming they are derived from this. 
TIS21-4904
=> fix: broken test

components/common/PanelsCreator.tsx, components/placements/OtherSites.tsx, cypress/component/placements/Placements.cy.tsx, mock-data/trainee-profile.ts, models/Placement.ts, package-lock.json, package.json, utilities/Constants.ts
Add "Other Sites" to the Placement panel, showing each "Site Known As" and "Site Location".
The site name is excluded to avoid overcrowding the panel, but the underlying data remains available in the profile.
TIS21-4971
TIS21-4396
=> feat: display other sites on placement panel

.github/workflows/README.md
Document the required AWS permissions for running the deployment workflow.
Specifically, those required to:
- Back up build artifacts to S3
- Deploy static website content to S3
- Update the CloudFront distribution
TIS21-4996
TIS21-4949
=> docs: required permissions for deploy workflow

.github/workflows/deploy.yml
Using the `clear-runs` workflow from .github repo to reject outdated runs. Environment `prod` is passed in to trigger clear-runs after prod deployment approval.
The PR is a draft one as it needs to wait until this [PR on .github repo](https://github.com/Health-Education-England/.github/pull/51) is merged.
TIS21-1209
TIS21-5130
=> chore: clear outdated runs in deploy workflow

components/forms/AutosaveMessage.tsx, components/forms/SubmittedFormsList.tsx, cypress/component/forms/AutosaveMessage.cy.tsx, cypress/component/forms/SubmittedFormsList.cy.tsx, cypress/component/forms/formr-part-a/FormA.cy.tsx, cypress/component/forms/formr-part-a/View.cy.tsx, cypress/component/forms/formr-part-b/View.cy.tsx, cypress/component/forms/formr-part-b/viewSections/ViewSection2.cy.tsx, cypress/component/forms/formr-part-b/viewSections/ViewSection4.cy.tsx, package-lock.json, package.json, redux/slices/formASlice.ts, redux/slices/formBSlice.ts, utilities/DateUtilities.ts, utilities/FormRUtilities.tsx, utilities/__test__/DateUtilities.test.ts
With an eye on the main bit of FE work for the DSP timestamp ticket https://hee-tis.atlassian.net/browse/TIS21-5138, the aim of this ticket is to have a consistent way of displaying the London time zone date/time minus the need to hardcode the time zone part (we currently add 'GMT' to all form submission dates whatever the season which is a bit 💩).
**Proposed solution** 
- Create a function to convert the UTC date to the London time zone (BST/GMT) date..
- Use this function to display a form submission date (without the seconds in the 'time' part as is - but we may want to change this?), and an autosave timestamp (with the seconds included in the 'time' part as is).
- The function now checks if the given date falls within an “ambiguous” period (between 1am and 2am on the last Sunday in …
=> From UTC to London (time zone) minus the fudge 

components/dsp/DspIssueBtn.tsx, cypress/component/dsp/CredentialIssue.cy.tsx, cypress/component/dsp/CredentialIssued.cy.tsx, cypress/component/dsp/CredentialVerify.cy.tsx, mock-data/dsp-credentials.ts, package.json
Replace .find with .findIndex in chooseProfileArr (DspIssueBtn.tsx) - which plays nicely with union types.
Fix a few more non-blocking Type errors in the test files and tidy-up the dsp-credential mock data (no need for revokedAt null value and explicitly typed undefined in the CredentialDsp object).
=> fix: Build Type error

components/forms/formr-part-b/ValidationSchema.ts, cypress/component/forms/formr-part-b/Section2.cy.tsx, package-lock.json, package.json
The TOOT fields are limited to three digits, but that is too restrictive for those that may have been on long term leave between Form R submissions.
Increase the limit to 9999, allowing any four digit number gives a large maximum without having to pick an arbitrary limit. Maintaining at least some restriction avoids obvious mistakes or bad data being entered.
TIS21-5293
=> fix: TOOT limited to 999

next.config.js, package.json
⚠ "next export" is deprecated in favor of "output: export" in next.config.js https://nextjs.org/docs/advanced-features/static-html-export
TIS21-5307
=> chore: remove deprecated 'next export'

.github/workflows/pr-analysis.yml
Sonar will shortly stop accepting scans done using java version 11.
Update the sonarcloud action to use the latest.
TIS21-SHED
=> build: update sonar action version

components/forms/formr-part-b/viewSections/View.tsx, cypress/e2e/formr-b/FormRB.spec.ts, package-lock.json, package.json
this has been re-enabled because when a form has been unsubmitted or is in draft and the user has already compleated the covid declaration section before the switch, the user will lose the ability to alter their covid section and will be stuck with their previous changes. which they will also still be able to view.
TIS21-5513
=> feat: re-enable covid declaration flag

components/forms/FormsListBtn.tsx, models/LifeCycleState.ts, package-lock.json, package.json, utilities/ActionSummaryUtilities.ts
**Problem**
Forms service API fetch currently includes the DELETED lifecycle state which has nobbled the FE Action Summary.
**Solution**
Refactor isAnyFormInProgress util function so it only filters draft and unsubmitted lifecycle states. 
(Also, a bit of boy-scouting...remove unused local lifecycle state from enum).
NO TICKET
=> Un-nobble the in-progress Action Summary logic

components/forms/form-builder/form-r/part-a/formAValidationSchema.ts, package-lock.json, package.json, utilities/ActionSummaryUtilities.ts, utilities/__test__/DateUtilities.test.ts
...where the user submits a form in e.g. Hawaii (UTC -10:00) timezone at say 10pm on 10/01/2024, which BE saves as 8am 11/01/2024 UTC. The result is a latest submitted 'future' form not being displayed in the Action Summary. Easiest fix is to remove the future constraint from the utils function logic (not sure why it was there in the first place tbh).
Also, after carefully considering the 'Doogie Howser, M.D. factor' with my learned colleague, R. Roberts esq. ,make the legalAge text match the D.O.B. validation logic (18+) - which in turn matches the BE validation logic.
NO TICKET
=> fix: the 'Hawaii problem'

components/forms/form-builder/form-r/part-a/formAValidationSchema.ts, package-lock.json, package.json
...from WTE validation schema. This might be a legacy thing but can't see the WTE type ever being null. Not saying this fixes the WTE issue but might narrow the focus.
NO TICKET
=> chore: remove redundant WTE .nullable() validation

components/forms/form-builder/FormBuilder.tsx, components/forms/form-builder/FormViewBuilder.tsx, components/forms/form-builder/form-r/part-a/FormAView.tsx, components/forms/form-builder/form-r/part-a/formAValidationSchema.ts, cypress/component/forms/formr-part-a/View.cy.tsx, package-lock.json, package.json
First iteration...
This commit is in preparation for https://hee-tis.atlassian.net/browse/TIS21-5578 
1. Display error summary box listing field errors
2. Use CSS to indicate individual field error
3. Disable the form submit button until errors are cleared
Had to tweak the visibility of elements displayed in the View component to ensure that all fields with errors are displayed. Next iteration will include better displayListValue logic to put 'N/A' next to a field name rather than 'None provided' where the conditional field logic determines this.
Also, future iterations can look to provide the same validation for Form B View.
NO TICKET
=> feat: Add validation to Form A View #1

components/forms/TextInputField.tsx, package-lock.json, package.json
The year section of the date picker was allowing an excess of numbers due to the layout of the date being yyyy/dd/mm instead of yyyy/mm/dd
When trying to create tests to check if more than 4 digits could be entered into the field, it was found that cypress was unable to enter the values into the date picker in such a way that would allow individual digits to be added. 
TIS21-5645
=> Fix  date configuration on text input field date picker

components/forms/MobilePhoneInputField.tsx, components/forms/form-builder/FormBuilder.tsx, components/forms/form-builder/FormViewBuilder.tsx, components/forms/form-builder/form-array/PanelBuilder.tsx, components/forms/form-builder/form-fields/Dates.tsx, components/forms/form-builder/form-fields/FieldErrorInline.tsx, components/forms/form-builder/form-fields/Phone.tsx, components/forms/form-builder/form-fields/Radios.tsx, components/forms/form-builder/form-fields/Selector.tsx, components/forms/form-builder/form-fields/Text.tsx, components/forms/form-builder/form-r/part-a/FormAView.tsx, components/forms/form-builder/form-r/part-a/formAValidationSchema.ts, components/forms/formr-part-b/sections/Declarations.tsx, components/home/actionSummary/ActionSummary.tsx, cypress/component/forms/formr-part-a/FormA.cy.tsx, cypress/component/forms/formr-part-a/View.cy.tsx, cypress/e2e/formr-a/FormRA.spec.ts, package-lock.json, package.json, styles/globals.scss, utilities/FormBuilderUtilities.ts, utilities/ProfileUtilities.ts, utilities/hooks/useFormAutosave.ts
**The main objective of this commit** 
1. Make sure Form R (Part A) still works while adding the necessary logic to the FormBuilder to accommodate dynamic arrays of objects (e.g. used in Form R Part B section 2). 
**This commit includes the following:**
1. Refactor of the FormBuilder component to allow arrays 
3. Create a PanelBuilder component to allow the us to render a dynamic array of panels, the ability to add and remove panels, and the validation of nested panel fields.
4. Rework the FormErrors error summary component to allow us to display nested array object field errors under the parent name/number.
3. Following discussion, trigger and display Inline errors in any form built via the FormBuilder as per the current Form R B implementation i.e. any field errors for the section …
=> refactor: FormBuilder logic to handle panel arrays (step 1 of about 4)

components/forms/form-builder/Declarations.tsx, components/forms/form-builder/FormBuilder.tsx, components/forms/form-builder/form-r/part-a/FormAView.tsx, components/forms/form-builder/form-r/part-a/formA.json, cypress/component/forms/formr-part-a/View.cy.tsx, cypress/e2e/formr-a/FormRA.spec.ts, package-lock.json, package.json
**Problem**
There is currently no consistency with Form R submission declarations.
Form A currently has a warning callout with a "by submitting this form..." declaration, with no mention of any agreements on the submitted form View page, while Form B does have checkboxes to tick as part of the main form.
**Solution** 
1. Standardise the submission checklist so the checklist fields and text can be passed in via the JSON file to a self-contained Declarations component.
2. Simplify the checkbox validation logic i.e. ‘Submit Form’ button is disabled unless all checkboxes have been checked (with no need for additional form validation).
Note: Some of the submit logic added to `FormAView.tsx` has been copied from the existing logic in `formr-part-b/sections/Declarations.tsx` .
TO DO:
There's …
=> Add submission declarations checklist to FormBuilder 

components/notifications/NotificationMessageText.tsx, cypress/component/notifications/NotificationMessageText.cy.tsx, package-lock.json, package.json
The in-app notification message contents is rendered as plain text, making them difficult to read.
The notification message will be modified to return as a HTML fragment, so the notification message component should be modified to use the fragment as inner html.
Add DOMPurify as a dependency and use it to sanitize the fragment before inserting it in to the DOM.
TIS21-5898
TIS21-5900
=> fix: improve in-app notification formatting

cypress/e2e/notifications/Notifications.spec.ts, package-lock.json, package.json
to the notifications tests
If this doesn't work then I 🔥 it to the ground.
NO TICKET
=> chore: Add 30s request and response timeouts

components/forms/form-builder/form-r/part-b/formBValidationSchema.ts, package-lock.json, package.json
A single day locum shift will start and end on the same day, currently that fails the Form R validation rules.
Update the validation to allow the start date and end date to be the same, it should still fail if the end date is before the start date.
TIS21-6084
=> fix: unable to record one day locum

.github/workflows/deploy.yml
Sonar analysis is failing as the repo is not checked out. Perform a checkout with deep clone before attempting to run sonar.
NO-TICKET
=> chore: fix sonar analysis

components/common/ExpanderMsg.tsx, components/common/PanelsCreator.tsx, components/forms/cct/CalcForm.tsx, components/forms/cct/Cct.tsx, components/programmes/CctBtn.tsx, cypress/component/forms/cct/Cct.cy.tsx, cypress/component/programmes/Programmes.cy.tsx, package-lock.json, package.json, redux/slices/cctCalcSlice.ts, styles/globals.scss, utilities/CctUtilities.ts, utilities/__test__/CctUtilities.test.ts
feat: update cct btn wording to better reflect the action
chore: add calcDefaultPropStartDate util (mainly to address the '>16 weeks future programme' issue).
chore: set the draggable cct dialog boundary to parent component to stop it getting completely hidden and unclickable.
chore: make the expander message text less wordy.
chore: add line breaks to disclaimer text (to stop some Safari weirdness with dialog width/print preview (to save PDF)
TIS21-6118
=> feat: polish the CCT MVP(1)

components/forms/cct/CalcForm.tsx, components/forms/cct/Cct.tsx, components/forms/cct/PrintableCct.tsx, components/programmes/CctBtn.tsx, cypress/component/forms/cct/Cct.cy.tsx, cypress/component/forms/cct/PrintableCct.cy.tsx, package-lock.json, package.json, redux/slices/cctCalcSlice.ts, styles/globals.scss
Problem: 
If there are a few programmes and the user scrolls to the end and clicks 'open CCT calc', the CCT dialog will open but will not be in view.
Fix: 
Use `window.scrollY` value to align the dialog with the y scroll position so the CCT calc is always in view even when when/if a btn click happens down the page. 
This involves using `defaultPosition` prop rather than `position` - which then means we can't use `position` prop to reset the dialog to 0,0 when printing (clicking 'save PDF') i.e. `defaultPosition` only works on first render.
Best solution is to make a separate `PrintableCct` comp using basic HTML that we can position and render more consistently. This involves only rendering it when `shouldPrint` is `true` and also keeping the contents hidden except when printing (via CSS …
=> fix: default dialog position

components/authentication/signup/sharedPrimitives/AuthBtnLink.tsx, components/common/ToastMessage.tsx, components/common/__test__/ToastMessage.test.tsx, components/support/TechSupport.tsx, components/support/__test__/TechSupport.test.tsx, cypress/e2e/authenticator/Authenticator.spec.ts, package-lock.json, package.json
The `@hee.nhs.uk` email address is no longer functional due to IT changes, update the support links to use a new `@nhs.net` address for support.
TIS21-6234
=> fix: update support email address

models/IDateBoxed.ts, models/Placement.ts, models/ProgrammeMembership.ts, package.json, redux/slices/dspSlice.ts
And more importantly, fix for 
```
/components/dsp/DspIssueBtn.tsx:132:33
Type error: Property 'tisId' does not exist on type 'IDateBoxed'.
130 |       : store.getState().traineeProfile.traineeProfileData.placements;
131 |   const matchedIndex = profileArr.findIndex(
> 132 |     (pObj: ProfileType) => pObj.tisId === id
|                                 ^
133 |   );
134 |   const matchedProfile = profileArr[matchedIndex];
135 | 
```
=> fix: version bump

package-lock.json, package.json, utilities/Constants.tsx
Local office names have been updated to remove the "Health Education England" prefix.
Previously the new names were put in alongside the legacy names, now the migration is complete the legacy names can be removed.
TIS21-6418
TIS21-6420
=> refactor: remove legacy local offices names

cypress/e2e/profile/Profile.spec.ts, package.json
Trying to ensure the existing profile is in a known state for each test, since somehow the old 'set it back to what it was after updating it' code didn't seem to be working on stage, though it worked just fine locally 😁 
(and missing version bump)
TIS21-6346
=> fix: profile e2e tests

components/forms/FormSavePDF.tsx, components/forms/conditionOfJoining/CojView.tsx, components/forms/form-builder/FormView.tsx, cypress/component/forms/FormSavePDF.cy.tsx, cypress/component/forms/conditionOfJoining/CojView.cy.tsx, cypress/component/programmes/CoJReadOnlyView.cy.tsx, package-lock.json, package.json, services/FormsService.ts, services/__test__/FormsService.test.ts, utilities/FileUtilities.ts, utilities/__test__/FormBuilderUtilities.test.ts
Use the forms service to download a Conditions of Joining PDF instead of
relying on client/browser functionality.
The COJ PDF is generated on the server when signed, but past COJ have
not had PDFs generated. As such the endpoint accepts the programme
membership data as JSON, and will generated the PDF on-demand if it does
not already exist.
TIS21-6106
TIS21-6123
=> feat: download COJ PDF from Forms service

components/forms/form-builder/form-r/part-b/FormRPartB.tsx, cypress/component/programmes/CoJReadOnlyView.cy.tsx, cypress/e2e/formr-b/FormRB.spec.ts, package-lock.json, package.json
Given that the FormB test doesn't do much except click the link, the simplest fix is to move the pdfHelpLink click to a Cypress comp test that tests the same FormSavePDF comp (more reliable and better for test coverage too).
NO TICKET
=> fix: coj e2e test

components/forms/cct/CctCalcCreate.tsx, cypress/component/forms/cct/CctCalcCreate.cy.tsx, cypress/e2e/navbar/Navbar.spec.ts, cypress/e2e/placements/Placements.spec.ts, cypress/e2e/programmes/Programmes.spec.ts, cypress/support/commands.ts, package.json, utilities/Constants.tsx
- No past PM's are included in the CCT form 'linked programme' select options
- The CCT form is not rendered (and msg displayed instead) if there are:
1. No PM's
2. Only past PM's.
fix: e2e tests (forgot about stage data!)
1. PL/PM tests: swap the CCT calc journey from PL's to PM's which should work for now.
2. Navbar tests: target the correct element.
NO TICKET
=> feat: filter out past PM's

components/forms/cct/CctCalcCreate.tsx, cypress/component/forms/cct/CctCalcCreate.cy.tsx, cypress/e2e/placements/Placements.spec.ts, cypress/e2e/programmes/Programmes.spec.ts, cypress/support/commands.ts, package-lock.json, package.json, utilities/CctConstants.ts, utilities/Constants.tsx
- Make new CctConstants.ts file (rather than the .tsx file that causes issue with e2e test webpack compilation) to hold the cctCalcWarningsMsgs.
- fix: the targeting of the saved cct calc from list (as we can't rely on the number prefix on stage).
Testing is 💩
NO TICKET
=> fix: e2e webpack compile error.

components/forms/AutosaveMessage.tsx, components/forms/CreateList.tsx, components/forms/StartOverButton.tsx, components/forms/__test__/StartOverButton.test.tsx, components/forms/cct/CctCalcSummary.tsx, components/forms/form-builder/FormBuilder.tsx, components/forms/form-builder/FormView.tsx, components/forms/form-builder/FormViewBuilder.tsx, components/forms/ltft/Ltft.tsx, components/forms/ltft/LtftForm.tsx, components/forms/ltft/LtftFormView.tsx, components/forms/ltft/LtftHome.tsx, components/forms/ltft/ltft.json, cypress/component/forms/ltft/LtftHome.cy.tsx, mock-data/mock-ltft-data.ts, package-lock.json, package.json, redux/slices/formsSlice.ts, redux/slices/ltftSlice.ts, redux/slices/ltftSummaryListSlice.ts, services/FormsService.ts, utilities/Constants.tsx, utilities/FormBuilderUtilities.ts, utilities/__test__/FormBuilderUtilities.test.ts, utilities/__test__/LtftUtilities.test.ts, utilities/hooks/__test__/useLtftHomeStartover.test.tsx, utilities/hooks/useFormAutosave.ts, utilities/hooks/useLtftHomeStartover.ts, utilities/ltftUtilities.ts
Please see https://hee-tis.atlassian.net/browse/TIS21-6974 for ACs .
Hints 'n tips
Probably a good idea to open Redux dev tools in the browser to step through the updates from the very beginning of the LTFT journey... snapshot, initial ltft obj population, updates etc. (the functions for this initial bit and subsequent DTO mapping can be found in ltftUtilities.ts).
Ltft form POST/PUT logic is handled via a generic saveDraftForm function (which has parameters to determine if e.g. autosave, which will in turn determine the thunk call in the redux slice).
NOTE: The redux slice boilerplate is very verbose atm - probably 500 lines just for this! So we can probably refactor this later.
The addition of the newFormId (see ltftSlice) is a bit confusing. It is created after autosave POST success to …
=> Save, update, review & delete DRAFT LTFT

components/forms/AutosaveMessage.tsx, components/forms/form-builder/FormBuilder.tsx, components/forms/form-builder/FormView.tsx, components/forms/ltft/LtftFormView.tsx, components/forms/ltft/LtftNameModal.tsx, components/forms/ltft/__test__/LtftFormView.test.tsx, components/forms/ltft/__test__/LtftNameModal.test.tsx, cypress/component/forms/ltft/LtftFormView.cy.tsx, package-lock.json, package.json, redux/slices/__test__/ltftSlice.test.ts, redux/slices/ltftSlice.ts, utilities/FormBuilderUtilities.ts, utilities/__test__/FormBuilderUtilities.test.ts, utilities/__test__/FormBuilderUtilitiesSaveDraftForm.test.ts, utilities/hooks/useFormAutosave.ts
NOTE: Mostly test files. The implementation code changes (~50 lines) is [here](https://github.com/Health-Education-England/tis-trainee-ui/pull/1166/commits/1a3622ca3a9edec8d3c3b6f108c267a5e30fbc2c) and [here](https://github.com/Health-Education-England/tis-trainee-ui/pull/1166/commits/1a3622ca3a9edec8d3c3b6f108c267a5e30fbc2c) .
As agreed Friday: 
1. Add an intermediate POST/PUT `/save /update` step on the `LtftFormView.tsx` submit button.
2. A successful save will open the 'are-you-sure' modal (still named` LtftNameModal.tsx` out of respect/laziness) minus the success Toast so as not to confuse the user (see  
showFailToastOnly in saveDraftForm).
3. A failed save will show error Toast and no modal with the user remaining on `LtftFormView.tsx` .
4. A modal submit will trigger the usual PUT …
=> Refactor LTFT submit

components/forms/ltft/LtftForm.tsx, components/forms/ltft/LtftFormView.tsx, components/forms/ltft/LtftStatusDetails.tsx, components/forms/ltft/LtftSummary.tsx, cypress/component/forms/ltft/LtftForm.cy.tsx, cypress/component/forms/ltft/LtftFormView.cy.tsx, mock-data/mock-ltft-data.ts, package.json, utilities/StringUtilities.ts, utilities/ltftUtilities.ts
The Status Details section is added in the Form and FormView for any non-DRAFT applications.
- new component for the Status Details section
- the `modifiedBy`, `reason`, and `message` fiels will only displayed in UNSUBMITTED or WITHDRAWN applications when they are not empty
- `capitalize` function in stringUtilities
- `getStatusReasonLabel` function in ltftUtilities
SUBMITTED:
UNSUBMITTED / WITHDRAWN:
TIS21-6706
TIS21-7145
=> feat: add status details in Form View

components/forms/cct/CctCalcCreate.tsx, mock-data/mock-cct-data.ts, mock-data/mock-ltft-data.ts, package-lock.json, package.json, redux/slices/cctSlice.ts, redux/slices/ltftSlice.ts, utilities/__test__/LtftUtilities.test.ts, utilities/ltftUtilities.ts
The LTFT notifications require the managing deanery name to determine which contacts/links to include in the notification. The details and forms services have been updated to include the managing deanery in the CCT calculation and LTFT dtos respectively.
Update the frontend models to include the managing deanery and populate the LTFT form's value based on the value taken from the CCT calculation.
TIS21-6596
TIS21-6594
=> feat(ltft): include managing deanery in LTFT

components/forms/cct/CctHome.tsx, components/forms/cct/CctSavedDrafts.tsx, components/forms/cct/CctSavedDraftsTable.tsx, components/home/Home.tsx, components/main/GlobalAlert.tsx, components/main/Main.tsx, components/navigation/TSSHeader.tsx, cypress/component/forms/cct/CctSavedDrafts.cy.tsx, cypress/component/home/Home.cy.tsx, cypress/component/navigation/TSSHeader.cy.tsx, cypress/component/programmes/Programmes.cy.tsx, mock-data/mock-ltft-data.ts, package-lock.json, package.json, redux/slices/userSlice.ts, utilities/hooks/__test__/useLtftHomeStartover.test.tsx, utilities/hooks/useCriticalDataLoader.ts, utilities/hooks/useIsBetaTester.ts, utilities/hooks/useIsLtftPilot.ts, utilities/hooks/useLtftHomeStartover.ts
Refactor auth data fetch:
- rename `getCognitoGroups` thunk to `fetchUserAuthInfo` and use this to fetch the `user.features` data.
- Create a new hook `useIsLtftPilot` to check if the user is a LTFT pilot member.
- Delete the old `useIsBetaTester` hook (as the logic is now part of the feature flag BE logic) and all references to it and reference the new `useIsLtftPilot` hook instead to conditionally render the LTFT stuff.
[TIS21-7200](https://hee-tis.atlassian.net/browse/TIS21-7200)
[TIS21-7200]: https://hee-tis.atlassian.net/browse/TIS21-7200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature Flag - Show LTFT to pilot regions (and beta tester club members)

components/forms/cct/CctSavedDraftsTable.tsx, components/forms/form-builder/form-sections/ImportantText.tsx, components/forms/ltft/LtftSummary.tsx, components/navigation/TSSHeader.tsx, components/notifications/RowActions.tsx, cypress/component/forms/ltft/LtftForm.cy.tsx, package-lock.json, package.json, styles/globals.scss
refactor: Slightly Increase the width of the page container from 960px to 990px to accommodate the table contents on desktop without needing to scroll. 
refactor: table layout to make it consistent across the app and style it some more.
fix: Remove `ImportantText` relating to TPD email in LTFT main application (section 1).
JFDI
=> refactor: page container width

components/main/Main.tsx, package-lock.json, package.json, utilities/hooks/useCriticalDataLoader.ts
Move the user auth actions from the useCriticalDataLoader back to Main so a user failed state (from any source e.g. totp token error) does not stop the app from being displayed.
JFDI
=> fix: user error state

components/common/ActionModal.tsx, components/forms/cct/CctSavedDraftsTable.tsx, components/forms/cct/__test__/CctSavedDraftsTable.test.tsx, components/forms/ltft/LtftFormView.tsx, components/forms/ltft/LtftSummary.tsx, cypress/component/common/ActionModal.cy.tsx, cypress/component/forms/cct/CctSavedDrafts.cy.tsx, cypress/component/forms/ltft/LtftHome.cy.tsx, package-lock.json, package.json, utilities/Constants.tsx, utilities/hooks/useActionState.ts
Another thing spotted on stage with slow internet connection...
Pass in isSubmitting state as prop to the ActionModal component to disable the dialog modal btn and display the correct btn text when the form is submitting.
Change the ordering of the modal close so that the submission logic runs first before closing the modal to ensure that the dialog modal button is still visible until the submission logic concludes.
Delete now redundant btn disable logic in the RowCctActions as it is now handled in the ActionModal component.
Note: the previous btn disable logic in the dialog modal did not work because the useSubmitting hook in the ActionModal component was not accessing the correct state value set in the parent component and so would always be false.
TIS21-7221
=> Fix/action modal button isSubmitting state

components/forms/cct/CctCalcCreate.tsx, components/forms/cct/CctHome.tsx, components/forms/ltft/LtftDeclarationsModal.tsx, package-lock.json, package.json, utilities/Constants.tsx
When clicking support prompts on pages such as the CCT Calculator the trainee is routed to the support page in the current tab, potentially losing progress/track of what they were doing.
NO-TICKET
=> fix: open in-page support links in new tab/window

components/common/ActionModal.tsx, components/forms/ltft/LtftStatusDetails.tsx, components/forms/ltft/LtftSummary.tsx, cypress/component/forms/ltft/LtftFormView.cy.tsx, cypress/component/forms/ltft/LtftSummary.cy.tsx, mock-data/mock-ltft-data.ts, package.json, styles/globals.scss, utilities/Constants.tsx, utilities/ltftUtilities.ts
What is included:
- Show REJECTED application with reason in `Previous Application` table on TSS LTFT tab
- Remove `Created` column in summary tables
- Change `Updated` column header to `Last Updated`
- Summary table filter of REJECTED status
- Shown REJECTED application form detail when row click on summary table
- Display date without timestamp in `Last Updated` column, but shown detailed time when mouseover
- Fix logic of `getStatusReasonLabel()` for UNSUBMITTED and WITHDRAWN to show actual value of reason if no matched label instead of "other". (This fix the value mismatch when LTFT is unsubmitted from TIS with reason `Proposed start date` being shown as `other reason`)
TIS21-7524
TIS21-7573
TIS21-7575
TIS21-7576
TIS21-7577
=> feat: show rejected LTFT
